import { type ContestCli } from './contest-cli.ts';
import type { ContestData, ContestIdentity, ContestInspection, ContestPlan, ContestPrepareRequest, ContestQuery, ContestStatus } from './contest-types.ts';
export declare function sameContest(a: ContestIdentity | undefined, b: ContestIdentity | undefined): boolean;
export declare function contestQueryArgs(input: ContestQuery): string[];
export declare class ContestService {
    private readonly cli;
    readonly root: string;
    private state;
    private loaded?;
    private tail;
    private saving;
    private controller;
    private phase;
    private message;
    private latestVersion?;
    private ready;
    private generation;
    private currentRules;
    private lastInspection?;
    constructor(cli: ContestCli, dshHome?: string);
    private load;
    private save;
    private exclusive;
    private assertEnabled;
    private runtime;
    private run;
    status(sessionId?: string): Promise<ContestStatus>;
    setEnabled(enabled: boolean): Promise<ContestStatus>;
    connect(): Promise<ContestStatus>;
    private install;
    private validateIdentity;
    researchIdentity(expected?: ContestIdentity): Promise<ContestIdentity>;
    private assertReady;
    rules(): Promise<string>;
    isEnabled(): boolean;
    rulesText(): string;
    query(input: ContestQuery, expected?: ContestIdentity, signal?: AbortSignal): Promise<ContestData>;
    inspect(identity: ContestIdentity, signal?: AbortSignal): Promise<ContestInspection>;
    inspection(identity: ContestIdentity): ContestInspection | undefined;
    checkUpdate(): Promise<ContestStatus>;
    update(): Promise<ContestStatus>;
    disconnect(): Promise<ContestStatus>;
    prepare(input: ContestPrepareRequest, identity: ContestIdentity, signal?: AbortSignal): Promise<ContestPlan>;
    execute(id: string, sessionId: string): Promise<ContestPlan>;
    dismiss(id: string, sessionId: string): Promise<ContestStatus>;
    private findPlan;
    reconcile(id: string, sessionId: string): Promise<ContestPlan>;
    dispose(): void;
}
//# sourceMappingURL=contest-service.d.ts.map