import type { JsonValue } from '@deepseek-ai/dsh-util-values';
import type { ContestIdentity } from './contest-types.ts';
import { type FactorRuntime } from './factor-contest-cli.ts';
import { type FactorCandidate, type FactorContestStatus, type FactorCredentials, type FactorInspection, type FactorPlan, type FactorPlanAction, type FactorQuery, type FactorRun } from './factor-contest-types.ts';
export declare class FactorContestService {
    private readonly runtime;
    readonly root: string;
    private state;
    private loaded?;
    private tail;
    private saving;
    private controller;
    private generation;
    private ready;
    private phase;
    private message;
    private latestVersion?;
    private inspection?;
    constructor(runtime: FactorRuntime, dshHome?: string);
    private load;
    private save;
    private exclusive;
    private assertReady;
    private call;
    private cli;
    private arena;
    private verify;
    private invalidate;
    isEnabled(): boolean;
    status(sessionId?: string): Promise<FactorContestStatus>;
    mode(enabled: boolean): Promise<FactorContestStatus>;
    connect(credentials?: FactorCredentials): Promise<FactorContestStatus>;
    disconnect(): Promise<FactorContestStatus>;
    private install;
    checkUpdate(): Promise<FactorContestStatus>;
    update(): Promise<FactorContestStatus>;
    researchIdentity(expected?: ContestIdentity): Promise<ContestIdentity>;
    private balance;
    private pool;
    private inspectCurrent;
    inspect(expected?: ContestIdentity, signal?: AbortSignal): Promise<FactorInspection>;
    query(input: FactorQuery, expected?: ContestIdentity, signal?: AbortSignal): Promise<JsonValue>;
    private snapshot;
    private validatePoolAction;
    prepare(sessionId: string, input: FactorPlanAction, expected?: ContestIdentity): Promise<FactorPlan>;
    confirm(planId: string, sessionId: string): Promise<FactorPlan>;
    private mutation;
    dismiss(planId: string, sessionId: string): Promise<void>;
    stopBudget(budgetId: string): Promise<void>;
    runCandidate(sessionId: string, budgetId: string, input: FactorCandidate, expected: ContestIdentity, signal?: AbortSignal): Promise<FactorRun>;
    reconcileRun(runId: string): Promise<FactorRun>;
    reconcilePlan(planId: string): Promise<FactorPlan>;
    dispose(): void;
}
//# sourceMappingURL=factor-contest-service.d.ts.map