/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_panda_connector_pandaConnector_bootstrap_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_checkForUpdates_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_describe_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_login_parameter_0$schema = z.object({
  'account': z.union([z.object({
  'kind': z.literal("phone").readonly(),
  'countryCallingCode': z.string().readonly().optional(),
  'nationalNumber': z.string().readonly(),
}), z.object({
  'kind': z.literal("email").readonly(),
  'email': z.string().readonly(),
}), z.object({
  'kind': z.literal("username").readonly(),
  'username': z.string().readonly(),
})]).readonly(),
  'password': z.string().readonly(),
})
const _deepseek_ai_dsh_panda_connector_pandaConnector_login_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_logout_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_repair_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_rollback_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_panda_connector_pandaConnector_update_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'message': z.string().readonly(),
  'state': z.object({
  'phase': z.union([z.literal("not-ready"), z.literal("ready"), z.literal("connected")]).readonly(),
  'credentialPersistence': z.union([z.literal("os-keyring"), z.literal("session-only"), z.literal("unavailable")]).readonly(),
  'reconnectState': z.union([z.literal("idle"), z.literal("reconnecting"), z.literal("reauth-required")]).readonly(),
  'dataReadiness': z.union([z.literal("unavailable"), z.literal("unchecked"), z.literal("verified")]).readonly(),
  'lastDataValidatedAt': z.union([z.literal(null), z.number()]).readonly(),
  'executionReadiness': z.union([z.literal("ready"), z.literal("unavailable"), z.literal("unchecked")]).readonly(),
  'executionIsolation': z.union([z.literal(null), z.literal("full"), z.literal("partial")]).readonly(),
  'executionBackend': z.union([z.literal(null), z.literal("windows-acl"), z.literal("seatbelt"), z.literal("bwrap"), z.literal("landlock")]).readonly(),
  'lastExecutionCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'lastFailure': z.union([z.literal(null), z.object({
  'operation': z.union([z.literal("describe"), z.literal("check-for-updates"), z.literal("bootstrap"), z.literal("update"), z.literal("repair"), z.literal("rollback"), z.literal("login"), z.literal("logout"), z.literal("execution-check")]).readonly(),
  'code': z.union([z.literal("invalid-request"), z.literal("cancelled"), z.literal("python-unavailable"), z.literal("python-unsupported"), z.literal("sdk-not-ready"), z.literal("sdk-version-mismatch"), z.literal("bootstrap-failed"), z.literal("release-unavailable"), z.literal("update-not-available"), z.literal("update-failed"), z.literal("repair-failed"), z.literal("rollback-unavailable"), z.literal("incompatible-api"), z.literal("login-failed"), z.literal("data-validation-failed"), z.literal("credential-cleanup-failed"), z.literal("network-unavailable"), z.literal("logout-unsupported"), z.literal("logout-failed"), z.literal("execution-unavailable"), z.literal("worker-failed")]).readonly(),
  'occurredAt': z.number().readonly(),
})]).readonly(),
  'requiredSdkVersion': z.string().readonly(),
  'installedSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'latestSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'updateAvailable': z.boolean().readonly(),
  'rollbackSdkVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonVersion': z.union([z.literal(null), z.string()]).readonly(),
  'pythonSource': z.union([z.literal(null), z.literal("configured"), z.literal("uv-managed")]).readonly(),
  'apiFingerprint': z.union([z.literal(null), z.string()]).readonly(),
  'capabilities': z.union([z.literal(null), z.object({
  'authentication': z.boolean().readonly(),
  'marketData': z.boolean().readonly(),
  'indexData': z.boolean().readonly(),
  'marginData': z.boolean().readonly(),
})]).readonly(),
  'lastUpdateCheckedAt': z.union([z.literal(null), z.number()]).readonly(),
  'logoutSupported': z.boolean().readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-panda-connector',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/bootstrap',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'bootstrap',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_bootstrap_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":393,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/checkForUpdates',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'checkForUpdates',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_checkForUpdates_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":383,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/describe',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_describe_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":373,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/login',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'login',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaLoginRequest',
            schema: _deepseek_ai_dsh_panda_connector_pandaConnector_login_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_login_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":434,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/logout',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_logout_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":475,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/repair',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'repair',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_repair_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":413,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/rollback',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'rollback',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_rollback_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":423,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-connector#pandaConnector/update',
      service: 'pandaConnector',
      namespace: 'pandaConnector',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-connector/types#PandaConnectorResult',
        schema: _deepseek_ai_dsh_panda_connector_pandaConnector_update_result$schema,
      },
      sourceLocation: {"file":"packages/host/panda-connector/src/index.ts","line":403,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Serialized PandaData lifecycle service exported through Typert Remote.",
        "summary": "Serialized PandaData lifecycle service exported through Typert Remote.",
        "tags": [],
        "jsDoc": "/** Serialized PandaData lifecycle service exported through Typert Remote. */",
        "key": "pandaConnector",
        "exportName": "PandaConnector",
        "members": [
          {
            "kind": "method",
            "name": "runtimeBinding",
            "signature": "runtimeBinding(): PandaRuntimeBinding",
            "summary": "Return the exact connected runtime identity to freeze into a Session.",
            "jsDoc": "/**\n * Return the exact connected runtime identity to freeze into a Session.\n * @returns immutable binding for the active verified environment.\n */"
          },
          {
            "kind": "method",
            "name": "validateRuntimeBinding",
            "signature": "async validateRuntimeBinding(binding: PandaRuntimeBinding): Promise<void>",
            "summary": "Verify that a Session-recorded environment remains retained and executable with Host credentials.",
            "jsDoc": "/**\n * Verify that a Session-recorded environment remains retained and executable with Host credentials.\n * @param binding - exact runtime identity read from the Session log.\n */"
          },
          {
            "kind": "method",
            "name": "executePython",
            "signature": "executePython(request: PandaPythonExecutionRequest, signal?: AbortSignal): Promise<PandaScriptExecutionResult>",
            "summary": "Execute one authorized script through the exact Session runtime and an available Host confinement backend.",
            "jsDoc": "/**\n * Execute one authorized script through the exact Session runtime and an available Host confinement backend.\n * @param request - immutable runtime identity and canonical Host-authorized paths.\n * @param signal - execution lifetime.\n * @returns bounded process outcome without credential material.\n */"
          },
          {
            "kind": "method",
            "name": "describe",
            "signature": "@Remote describe(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Inspect the active SDK and restore persisted authentication.",
            "jsDoc": "/**\n * Inspect the active SDK and restore persisted authentication.\n * @param signal - Operation lifetime.\n * @returns Safe connector state.\n */"
          },
          {
            "kind": "method",
            "name": "checkForUpdates",
            "signature": "@Remote checkForUpdates(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Discover the latest official SDK release without changing the active environment.",
            "jsDoc": "/**\n * Discover the latest official SDK release without changing the active environment.\n * @param signal - Operation lifetime.\n * @returns Update metadata.\n */"
          },
          {
            "kind": "method",
            "name": "bootstrap",
            "signature": "@Remote bootstrap(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Install the latest official SDK into a new private environment.",
            "jsDoc": "/**\n * Install the latest official SDK into a new private environment.\n * @param signal - Operation lifetime.\n * @returns Activated connector state.\n */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote update(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Upgrade through candidate verification and pointer-only activation.",
            "jsDoc": "/**\n * Upgrade through candidate verification and pointer-only activation.\n * @param signal - Operation lifetime.\n * @returns Activated connector state.\n */"
          },
          {
            "kind": "method",
            "name": "repair",
            "signature": "@Remote repair(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Rebuild the active release without modifying the current environment in place.",
            "jsDoc": "/**\n * Rebuild the active release without modifying the current environment in place.\n * @param signal - Operation lifetime.\n * @returns Repaired connector state.\n */"
          },
          {
            "kind": "method",
            "name": "rollback",
            "signature": "@Remote rollback(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Restore the previously verified immutable environment.",
            "jsDoc": "/**\n * Restore the previously verified immutable environment.\n * @param signal - Operation lifetime.\n * @returns Rolled-back connector state.\n */"
          },
          {
            "kind": "method",
            "name": "login",
            "signature": "@Remote login(request: PandaLoginRequest, signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Authenticate and retain replay material in the OS credential store when available.",
            "jsDoc": "/**\n * Authenticate and retain replay material in the OS credential store when available.\n * @param request - explicit account form and write-only password.\n * @param signal - caller/connection lifetime.\n * @returns `connected` after the one-shot SDK login succeeds.\n */"
          },
          {
            "kind": "method",
            "name": "logout",
            "signature": "@Remote logout(signal?: AbortSignal): Promise<PandaConnectorResult>",
            "summary": "Clear Host-owned replay material and ask every retained SDK environment to log out.",
            "jsDoc": "/**\n * Clear Host-owned replay material and ask every retained SDK environment to log out.\n * @param signal - Operation lifetime.\n * @returns Verified disconnected state.\n */"
          },
          {
            "kind": "method",
            "name": "disposeConnector",
            "signature": "async disposeConnector(): Promise<void>",
            "summary": "Abort active work and drain the serialized lifecycle queue.",
            "jsDoc": "/** Abort active work and drain the serialized lifecycle queue. @returns settlement after all work has drained. */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "PandaAccount",
            "declaration": "export type PandaAccount = PandaPhoneAccount | PandaEmailAccount | PandaUsernameAccount;"
          },
          {
            "name": "PandaConnectionPhase",
            "declaration": "export type PandaConnectionPhase = 'not-ready' | 'ready' | 'connected';"
          },
          {
            "name": "PandaConnectionState",
            "declaration": "export interface PandaConnectionState {\n    readonly phase: PandaConnectionPhase;\n    readonly credentialPersistence: 'os-keyring' | 'session-only' | 'unavailable';\n    readonly reconnectState: 'idle' | 'reconnecting' | 'reauth-required';\n    readonly dataReadiness: PandaDataReadiness;\n    readonly lastDataValidatedAt: number | null;\n    readonly executionReadiness: PandaExecutionReadiness;\n    readonly executionIsolation: PandaExecutionIsolation | null;\n    readonly executionBackend: PandaExecutionBackend | null;\n    readonly lastExecutionCheckedAt: number | null;\n    readonly lastFailure: PandaConnectorFailureRecord | null;\n    readonly requiredSdkVersion: string;\n    readonly installedSdkVersion: string | null;\n    readonly latestSdkVersion: string | null;\n    readonly updateAvailable: boolean;\n    readonly rollbackSdkVersion: string | null;\n    readonly pythonVersion: string | null;\n    readonly pythonSource: PandaPythonSource | null;\n    readonly apiFingerprint: string | null;\n    readonly capabilities: PandaSdkCapabilities | null;\n    readonly lastUpdateCheckedAt: number | null;\n    readonly logoutSupported: boolean;\n}"
          },
          {
            "name": "PandaConnectorFailure",
            "declaration": "export interface PandaConnectorFailure {\n    readonly ok: false;\n    readonly code: PandaConnectorFailureCode;\n    readonly message: string;\n    readonly state: PandaConnectionState;\n}"
          },
          {
            "name": "PandaConnectorFailureCode",
            "declaration": "export type PandaConnectorFailureCode = 'invalid-request' | 'cancelled' | 'python-unavailable' | 'python-unsupported' | 'sdk-not-ready' | 'sdk-version-mismatch' | 'bootstrap-failed' | 'release-unavailable' | 'update-not-available' | 'update-failed' | 'repair-failed' | 'rollback-unavailable' | 'incompatible-api' | 'login-failed' | 'data-validation-failed' | 'credential-cleanup-failed' | 'network-unavailable' | 'logout-unsupported' | 'logout-failed' | 'execution-unavailable' | 'worker-failed';"
          },
          {
            "name": "PandaConnectorFailureRecord",
            "declaration": "export interface PandaConnectorFailureRecord {\n    readonly operation: PandaConnectorOperation;\n    readonly code: PandaConnectorFailureCode;\n    readonly occurredAt: number;\n}"
          },
          {
            "name": "PandaConnectorOperation",
            "declaration": "export type PandaConnectorOperation = 'describe' | 'check-for-updates' | 'bootstrap' | 'update' | 'repair' | 'rollback' | 'login' | 'logout' | 'execution-check';"
          },
          {
            "name": "PandaConnectorResult",
            "declaration": "export type PandaConnectorResult = PandaConnectorSuccess | PandaConnectorFailure;"
          },
          {
            "name": "PandaConnectorSuccess",
            "declaration": "export interface PandaConnectorSuccess {\n    readonly ok: true;\n    readonly state: PandaConnectionState;\n}"
          },
          {
            "name": "PandaDataReadiness",
            "declaration": "export type PandaDataReadiness = 'unchecked' | 'verified' | 'unavailable';"
          },
          {
            "name": "PandaEmailAccount",
            "declaration": "export interface PandaEmailAccount {\n    readonly kind: 'email';\n    readonly email: string;\n}"
          },
          {
            "name": "PandaExecutionBackend",
            "declaration": "export type PandaExecutionBackend = 'windows-acl' | 'seatbelt' | 'bwrap' | 'landlock';"
          },
          {
            "name": "PandaExecutionIsolation",
            "declaration": "export type PandaExecutionIsolation = 'full' | 'partial';"
          },
          {
            "name": "PandaExecutionReadiness",
            "declaration": "export type PandaExecutionReadiness = 'unchecked' | 'ready' | 'unavailable';"
          },
          {
            "name": "PandaLoginRequest",
            "declaration": "export interface PandaLoginRequest {\n    readonly account: PandaAccount;\n    readonly password: string;\n}"
          },
          {
            "name": "PandaPhoneAccount",
            "declaration": "export interface PandaPhoneAccount {\n    readonly kind: 'phone';\n    readonly countryCallingCode?: string;\n    readonly nationalNumber: string;\n}"
          },
          {
            "name": "PandaPythonExecutionRequest",
            "declaration": "export interface PandaPythonExecutionRequest {\n    readonly binding: PandaRuntimeBinding;\n    readonly sessionId: SessionId;\n    readonly workspaceRoot: string;\n    readonly scriptPath: string;\n    readonly args: readonly string[];\n    readonly workdir: string;\n}"
          },
          {
            "name": "PandaPythonSource",
            "declaration": "export type PandaPythonSource = 'configured' | 'uv-managed';"
          },
          {
            "name": "PandaRuntimeBinding",
            "declaration": "export interface PandaRuntimeBinding {\n    readonly environmentId: string;\n    readonly sdkVersion: string;\n    readonly pythonVersion: string;\n    readonly apiFingerprint: string;\n}"
          },
          {
            "name": "PandaScriptExecutionResult",
            "declaration": "export interface PandaScriptExecutionResult {\n    readonly exitCode: number;\n    readonly stdout: string;\n    readonly stderr: string;\n}"
          },
          {
            "name": "PandaSdkCapabilities",
            "declaration": "export interface PandaSdkCapabilities {\n    readonly authentication: boolean;\n    readonly marketData: boolean;\n    readonly indexData: boolean;\n    readonly marginData: boolean;\n}"
          },
          {
            "name": "PandaUsernameAccount",
            "declaration": "export interface PandaUsernameAccount {\n    readonly kind: 'username';\n    readonly username: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
