/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PandaConnectorResult, PandaLoginRequest } from '@deepseek-ai/dsh-panda-connector/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$70616e6461436f6e6e6563746f72 {
    bootstrap: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    checkForUpdates: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    describe: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    login: (request: PandaLoginRequest, signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    logout: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    repair: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    rollback: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    update: (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
  }
  interface TypertRemoteMap {
    'pandaConnector/bootstrap': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/checkForUpdates': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/describe': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/login': (request: PandaLoginRequest, signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/logout': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/repair': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/rollback': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
    'pandaConnector/update': (signal?: AbortSignal) => Promise<RemoteResult<PandaConnectorResult>>
  }
  interface TypertRemoteNamespaceMap {
    'pandaConnector': TypertRemoteNamespace$70616e6461436f6e6e6563746f72
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
