import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TradeLoop } from "./TradeLoop.js";
/** A view of received market data only; an empty or stale feed is never animated as live. */
export function FlyMarketView({ market, observing, onDetails }) {
    const prices = (market?.chart ?? []).filter(Number.isFinite);
    const low = Math.min(...prices), high = Math.max(...prices), range = high - low || 1;
    const points = prices.map((price, i) => `${20 + i / Math.max(1, prices.length - 1) * 720},${185 - (price - low) / range * 150}`).join(' ');
    const value = market?.price != null && Number.isFinite(market.price) ? market.price.toLocaleString('zh-CN', { maximumFractionDigits: 4 }) : '—';
    return _jsxs("div", { className: "fv-focus-grid", children: [_jsxs("section", { className: "fv-market-focus", "aria-label": "\u5F53\u524D\u5408\u7EA6\u884C\u60C5", children: [_jsxs("header", { children: [_jsxs("div", { children: [_jsx("small", { children: market?.readiness === 'ready' ? '当前行情' : '末次报价 · 等待有效行情' }), _jsx("h2", { children: market?.symbol || '选择一个实际合约' })] }), _jsx("strong", { className: "fv-market-price", children: value })] }), prices.length > 1 ? _jsxs("svg", { viewBox: "0 0 760 220", role: "img", "aria-label": `${market?.symbol} 已接收价格曲线，最低 ${low}，最高 ${high}`, children: [[35, 110, 185].map(y => _jsx("line", { x1: "20", x2: "740", y1: y, y2: y, stroke: "var(--fv-line)", strokeDasharray: "4 5" }, y)), _jsx("polyline", { points: points, fill: "none", stroke: "var(--fv-lime)", strokeWidth: "2.5", vectorEffect: "non-scaling-stroke" })] }) : _jsxs("div", { className: "fv-market-empty", children: [_jsx("span", { children: "\u7B49\u5F85\u884C\u60C5" }), _jsx("p", { children: "\u6709\u6548\u62A5\u4EF7\u5230\u8FBE\u540E\uFF0C\u5728\u8FD9\u91CC\u67E5\u770B\u4EF7\u683C\u53D8\u5316\u3002" })] }), _jsxs("footer", { children: [_jsxs("span", { children: [market?.period_minutes || 1, " \u5206\u949F\u6536\u76D8\u4EF7 \u00B7 ", market?.count ?? 0, " \u6839"] }), _jsx("span", { children: market ? `多 ${market.long ?? 0} / 空 ${market.short ?? 0} 手` : '持仓待同步' })] }), market?.quote_at && _jsxs("small", { className: "fv-quote-time", children: ["\u62A5\u4EF7\u65F6\u95F4 ", new Date(market.quote_at * 1000).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }), "\uFF08\u4E0A\u6D77\uFF09"] })] }), _jsxs("aside", { className: "fv-reason-focus", "aria-label": "\u5F53\u524D\u51B3\u7B56\u72B6\u6001", children: [_jsx("small", { children: "\u5F53\u524D\u8FDB\u5C55" }), _jsx(TradeLoop, { markets: market ? [market] : [], observing: observing }), _jsx("button", { type: "button", onClick: onDetails, children: "\u884C\u60C5\u4E0E\u8FD0\u884C\u8BE6\u60C5 \u2197" })] })] });
}
//# sourceMappingURL=FlyMarketView.js.map