import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const actions = { WAIT: '等待', LONG: '目标做多', SHORT: '目标做空', CLOSE: '平仓' };
const position = (n) => n === 0 ? '空仓' : `${n > 0 ? '多' : '空'} ${Math.abs(n)} 手`;
const readiness = { ready: '行情就绪', history_incomplete: '历史不足', history_gap: '分钟线有缺口', quote_stale: '等待 PandaAI 模拟赛 新报价', bars_stale: '分钟线过期' };
export function TradeLoop({ markets, observing }) {
    return _jsxs("div", { className: "fv-decisions", children: [!markets.length && _jsx("p", { className: "fv-note", children: "\u9009\u62E9\u5B9E\u9645\u5408\u7EA6\u540E\uFF0C\u5728\u8FD9\u91CC\u67E5\u770B\u4EA4\u6613\u9009\u62E9\u548C\u539F\u56E0\u3002" }), markets.map(m => {
                const d = m.decision;
                const waiting = m.readiness !== 'ready' ? readiness[m.readiness] || m.readiness : observing ? '交易建议未启动' : '等待下一轮神经决策';
                return _jsxs("article", { className: "fv-decision", children: [_jsxs("header", { children: [_jsx("strong", { children: m.symbol || m.product }), _jsx("span", { children: !observing && m.readiness === 'ready' && d ? actions[d.choice.action] || d.choice.action : '等待' })] }), d?.choice.target_position !== undefined && _jsxs("p", { children: [position(d.choice.current_position ?? 0), " \u2192 ", position(d.choice.target_position)] }), _jsx("p", { children: observing || m.readiness !== 'ready' || !d ? waiting : d.choice.reason }), _jsxs("small", { children: [m.execution?.message || (observing ? '未生成交易计划' : '有有效信号后生成待确认计划'), m.signal_filter && ` · ${m.signal_filter.reason}`] }), d && _jsxs("small", { children: ["\u6700\u8FD1\u51B3\u7B56 ", new Date(d.input_at * 1000).toLocaleTimeString(), " \u00B7 ", actions[d.choice.action] || d.choice.action] }), _jsxs("details", { children: [_jsx("summary", { children: "\u67E5\u770B\u4F9D\u636E" }), _jsxs("p", { children: [m.period_minutes || 1, " \u5206\u949F \u00B7 ", m.count, "/500 \u6839 \u00B7 ", readiness[m.readiness] || m.readiness] }), d && _jsxs(_Fragment, { children: [_jsxs("p", { children: ["\u51B3\u7B56\u7F16\u53F7 ", d.decision_id] }), Object.entries(d.trade_response || {}).map(([key, value]) => _jsxs("p", { children: [key, " \u00B7 \u6D3B\u8DC3 ", value.active, "/", value.neurons, " \u00B7 \u8BFB\u51FA ", value.value.toFixed(3)] }, key))] }), m.pending && _jsxs("p", { children: ["\u6210\u4EA4\u56DE\u62A5 ", m.pending.filled, " \u624B \u00B7 ", m.pending.terminal ? '委托已终结' : '等待柜台终态'] })] })] }, m.product);
            })] });
}
//# sourceMappingURL=TradeLoop.js.map