/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ContestData, ContestInspection, ContestPlan, ContestQuery, ContestSessionOpenRequest, ContestSessionOpenResult, ContestStatus, ModelAccessRequest, ModelAccessResponse, QuantSkillsAgentCreateRequest, QuantSkillsAgentDefinition, QuantSkillsAgentDeleteRequest, QuantSkillsAgentSessionArchiveItem, QuantSkillsAgentSessionCreateRequest, QuantSkillsAgentSessionCreateResult, QuantSkillsAgentTeamCreateRequest, QuantSkillsAgentTeamDefinition, QuantSkillsAgentTeamDeleteRequest, QuantSkillsAgentTeamSessionArchiveItem, QuantSkillsAgentTeamSessionCreateRequest, QuantSkillsAgentTeamSessionCreateResult, QuantSkillsAgentTeamUpdateRequest, QuantSkillsAgentUpdateRequest, QuantSkillsAuthoringCommitRequest, QuantSkillsAuthoringCommitResult, QuantSkillsAuthoringSessionCreateRequest, QuantSkillsFileAttachRequest, QuantSkillsFileListRequest, QuantSkillsFileListResult, QuantSkillsFileReadRequest, QuantSkillsFileReadResult, QuantSkillsFrequentRequest, QuantSkillsFrequentSkill, QuantSkillsLibrarySourceRecord, QuantSkillsPlainSessionArchiveItem, QuantSkillsPlainSessionCreateRequest, QuantSkillsPlainSessionCreateResult, QuantSkillsPromptFormListRequest, QuantSkillsPromptFormListResult, QuantSkillsPromptFormRenderRequest, QuantSkillsPromptFormRenderResult, QuantSkillsResidentSkillAttachRequest, QuantSkillsResidentSkillDetachRequest, QuantSkillsResidentSkillResult, QuantSkillsResultPrepareRequest, QuantSkillsResultPrepareResult, QuantSkillsResultPreview, QuantSkillsResultPreviewRequest, QuantSkillsSessionArchiveItem, QuantSkillsSessionCreateRequest, QuantSkillsSessionCreateResult, QuantSkillsSessionEnsureRequest, QuantSkillsSessionEnsureResult, QuantSkillsSessionFileAttachment, QuantSkillsSessionListRequest, QuantSkillsWorkspaceRequest, QuantSkillsWorkspaceResolveResult, QuantSkillsWorkspaceStatusResult } from '@deepseek-ai/dsh-quantskills-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7175616e74536b696c6c7353657373696f6e73 {
    agentCreate: (request: QuantSkillsAgentCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentDefinition>>
    agentDelete: (request: QuantSkillsAgentDeleteRequest) => Promise<RemoteResult<void>>
    agentLibrarySources: () => Promise<RemoteResult<readonly QuantSkillsLibrarySourceRecord[]>>
    agentList: () => Promise<RemoteResult<readonly QuantSkillsAgentDefinition[]>>
    agentSessionCreate: (request: QuantSkillsAgentSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentSessionCreateResult>>
    agentSessionList: (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsAgentSessionArchiveItem[]>>
    agentTeamCreate: (request: QuantSkillsAgentTeamCreateRequest) => Promise<RemoteResult<QuantSkillsAgentTeamDefinition>>
    agentTeamDelete: (request: QuantSkillsAgentTeamDeleteRequest) => Promise<RemoteResult<void>>
    agentTeamList: () => Promise<RemoteResult<readonly QuantSkillsAgentTeamDefinition[]>>
    agentTeamSessionCreate: (request: QuantSkillsAgentTeamSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentTeamSessionCreateResult>>
    agentTeamSessionList: (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsAgentTeamSessionArchiveItem[]>>
    agentTeamUpdate: (request: QuantSkillsAgentTeamUpdateRequest) => Promise<RemoteResult<QuantSkillsAgentTeamDefinition>>
    agentUninstall: (request: QuantSkillsAgentDeleteRequest) => Promise<RemoteResult<void>>
    agentUpdate: (request: QuantSkillsAgentUpdateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentDefinition>>
    authoringCommit: (request: QuantSkillsAuthoringCommitRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAuthoringCommitResult>>
    authoringSessionCreate: (request: QuantSkillsAuthoringSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentSessionCreateResult>>
    contestCheckUpdate: () => Promise<RemoteResult<ContestStatus>>
    contestConnect: () => Promise<RemoteResult<ContestStatus>>
    contestDisconnect: () => Promise<RemoteResult<ContestStatus>>
    contestDismiss: (request: { planId: string; sessionId: string; }) => Promise<RemoteResult<ContestStatus>>
    contestExecute: (request: { planId: string; sessionId: string; }) => Promise<RemoteResult<ContestPlan>>
    contestInspect: (request: { sessionId: SessionId; }, signal?: AbortSignal) => Promise<RemoteResult<ContestInspection>>
    contestMode: (request: { enabled: boolean; }) => Promise<RemoteResult<ContestStatus>>
    contestQuery: (request: ContestQuery) => Promise<RemoteResult<ContestData>>
    contestReconcile: (request: { planId: string; sessionId: string; }) => Promise<RemoteResult<ContestPlan>>
    contestSessionOpen: (request: ContestSessionOpenRequest, signal?: AbortSignal) => Promise<RemoteResult<ContestSessionOpenResult>>
    contestStatus: (request: { sessionId?: string; }) => Promise<RemoteResult<ContestStatus>>
    contestUpdate: () => Promise<RemoteResult<ContestStatus>>
    create: (request: QuantSkillsSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsSessionCreateResult>>
    fileAttach: (request: QuantSkillsFileAttachRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsSessionFileAttachment>>
    fileList: (request: QuantSkillsFileListRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsFileListResult>>
    fileRead: (request: QuantSkillsFileReadRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsFileReadResult>>
    frequent: (request: QuantSkillsFrequentRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsFrequentSkill[]>>
    list: (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsSessionArchiveItem[]>>
    modelsAccess: (request: ModelAccessRequest) => Promise<RemoteResult<ModelAccessResponse>>
    plainSessionCreate: (request: QuantSkillsPlainSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsPlainSessionCreateResult>>
    plainSessionList: (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsPlainSessionArchiveItem[]>>
    promptFormList: (request: QuantSkillsPromptFormListRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsPromptFormListResult>>
    promptFormRender: (request: QuantSkillsPromptFormRenderRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsPromptFormRenderResult>>
    residentSkillAttach: (request: QuantSkillsResidentSkillAttachRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResidentSkillResult>>
    residentSkillDetach: (request: QuantSkillsResidentSkillDetachRequest) => Promise<RemoteResult<QuantSkillsResidentSkillResult>>
    resultList: (request: { readonly sessionId: SessionId; }, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResultPrepareResult>>
    resultPrepare: (request: QuantSkillsResultPrepareRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResultPrepareResult>>
    resultPreview: (request: QuantSkillsResultPreviewRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResultPreview>>
    sessionEnsure: (request: QuantSkillsSessionEnsureRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsSessionEnsureResult>>
    workspaceResolve: (request: QuantSkillsWorkspaceRequest) => Promise<RemoteResult<QuantSkillsWorkspaceResolveResult>>
    workspaceStatus: (request: QuantSkillsWorkspaceRequest) => Promise<RemoteResult<QuantSkillsWorkspaceStatusResult>>
  }
  interface TypertRemoteMap {
    'quantSkillsSessions/agentCreate': (request: QuantSkillsAgentCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentDefinition>>
    'quantSkillsSessions/agentDelete': (request: QuantSkillsAgentDeleteRequest) => Promise<RemoteResult<void>>
    'quantSkillsSessions/agentLibrarySources': () => Promise<RemoteResult<readonly QuantSkillsLibrarySourceRecord[]>>
    'quantSkillsSessions/agentList': () => Promise<RemoteResult<readonly QuantSkillsAgentDefinition[]>>
    'quantSkillsSessions/agentSessionCreate': (request: QuantSkillsAgentSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentSessionCreateResult>>
    'quantSkillsSessions/agentSessionList': (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsAgentSessionArchiveItem[]>>
    'quantSkillsSessions/agentTeamCreate': (request: QuantSkillsAgentTeamCreateRequest) => Promise<RemoteResult<QuantSkillsAgentTeamDefinition>>
    'quantSkillsSessions/agentTeamDelete': (request: QuantSkillsAgentTeamDeleteRequest) => Promise<RemoteResult<void>>
    'quantSkillsSessions/agentTeamList': () => Promise<RemoteResult<readonly QuantSkillsAgentTeamDefinition[]>>
    'quantSkillsSessions/agentTeamSessionCreate': (request: QuantSkillsAgentTeamSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentTeamSessionCreateResult>>
    'quantSkillsSessions/agentTeamSessionList': (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsAgentTeamSessionArchiveItem[]>>
    'quantSkillsSessions/agentTeamUpdate': (request: QuantSkillsAgentTeamUpdateRequest) => Promise<RemoteResult<QuantSkillsAgentTeamDefinition>>
    'quantSkillsSessions/agentUninstall': (request: QuantSkillsAgentDeleteRequest) => Promise<RemoteResult<void>>
    'quantSkillsSessions/agentUpdate': (request: QuantSkillsAgentUpdateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentDefinition>>
    'quantSkillsSessions/authoringCommit': (request: QuantSkillsAuthoringCommitRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAuthoringCommitResult>>
    'quantSkillsSessions/authoringSessionCreate': (request: QuantSkillsAuthoringSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAgentSessionCreateResult>>
    'quantSkillsSessions/contestCheckUpdate': () => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/contestConnect': () => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/contestDisconnect': () => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/contestDismiss': (request: { planId: string; sessionId: string; }) => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/contestExecute': (request: { planId: string; sessionId: string; }) => Promise<RemoteResult<ContestPlan>>
    'quantSkillsSessions/contestInspect': (request: { sessionId: SessionId; }, signal?: AbortSignal) => Promise<RemoteResult<ContestInspection>>
    'quantSkillsSessions/contestMode': (request: { enabled: boolean; }) => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/contestQuery': (request: ContestQuery) => Promise<RemoteResult<ContestData>>
    'quantSkillsSessions/contestReconcile': (request: { planId: string; sessionId: string; }) => Promise<RemoteResult<ContestPlan>>
    'quantSkillsSessions/contestSessionOpen': (request: ContestSessionOpenRequest, signal?: AbortSignal) => Promise<RemoteResult<ContestSessionOpenResult>>
    'quantSkillsSessions/contestStatus': (request: { sessionId?: string; }) => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/contestUpdate': () => Promise<RemoteResult<ContestStatus>>
    'quantSkillsSessions/create': (request: QuantSkillsSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsSessionCreateResult>>
    'quantSkillsSessions/fileAttach': (request: QuantSkillsFileAttachRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsSessionFileAttachment>>
    'quantSkillsSessions/fileList': (request: QuantSkillsFileListRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsFileListResult>>
    'quantSkillsSessions/fileRead': (request: QuantSkillsFileReadRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsFileReadResult>>
    'quantSkillsSessions/frequent': (request: QuantSkillsFrequentRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsFrequentSkill[]>>
    'quantSkillsSessions/list': (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsSessionArchiveItem[]>>
    'quantSkillsSessions/modelsAccess': (request: ModelAccessRequest) => Promise<RemoteResult<ModelAccessResponse>>
    'quantSkillsSessions/plainSessionCreate': (request: QuantSkillsPlainSessionCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsPlainSessionCreateResult>>
    'quantSkillsSessions/plainSessionList': (request: QuantSkillsSessionListRequest, signal?: AbortSignal) => Promise<RemoteResult<readonly QuantSkillsPlainSessionArchiveItem[]>>
    'quantSkillsSessions/promptFormList': (request: QuantSkillsPromptFormListRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsPromptFormListResult>>
    'quantSkillsSessions/promptFormRender': (request: QuantSkillsPromptFormRenderRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsPromptFormRenderResult>>
    'quantSkillsSessions/residentSkillAttach': (request: QuantSkillsResidentSkillAttachRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResidentSkillResult>>
    'quantSkillsSessions/residentSkillDetach': (request: QuantSkillsResidentSkillDetachRequest) => Promise<RemoteResult<QuantSkillsResidentSkillResult>>
    'quantSkillsSessions/resultList': (request: { readonly sessionId: SessionId; }, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResultPrepareResult>>
    'quantSkillsSessions/resultPrepare': (request: QuantSkillsResultPrepareRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResultPrepareResult>>
    'quantSkillsSessions/resultPreview': (request: QuantSkillsResultPreviewRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsResultPreview>>
    'quantSkillsSessions/sessionEnsure': (request: QuantSkillsSessionEnsureRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsSessionEnsureResult>>
    'quantSkillsSessions/workspaceResolve': (request: QuantSkillsWorkspaceRequest) => Promise<RemoteResult<QuantSkillsWorkspaceResolveResult>>
    'quantSkillsSessions/workspaceStatus': (request: QuantSkillsWorkspaceRequest) => Promise<RemoteResult<QuantSkillsWorkspaceStatusResult>>
  }
  interface TypertRemoteNamespaceMap {
    'quantSkillsSessions': TypertRemoteNamespace$7175616e74536b696c6c7353657373696f6e73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
