import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { configuredInstrument, exchanges, products, withInstrument, withSymbol } from "./jev-templates.js";
import css from './ContestPage.module.css';
export function JevInstrument({ config, onChange, catalog = products, compact = false }) {
    const [search, setSearch] = useState('');
    const instrument = configuredInstrument(config, catalog);
    const known = catalog.some(item => item.product === instrument.product);
    const term = search.trim().toLowerCase();
    const visible = catalog.filter(item => item.product === instrument.product || `${item.name} ${item.product} ${item.exchange} ${exchanges[item.exchange]}`.toLowerCase().includes(term));
    const parameters = _jsxs(_Fragment, { children: [_jsxs("label", { children: ["\u4EA4\u6613\u6240", _jsx("select", { value: instrument.exchange, onChange: event => onChange(withInstrument(config, { ...instrument, exchange: event.target.value })), children: Object.entries(exchanges).map(([code, name]) => _jsx("option", { value: code, children: name }, code)) })] }), _jsxs("label", { children: ["\u6700\u5C0F\u4EF7\u683C\u53D8\u52A8\uFF08tick \u5BF9\u5E94\u4EF7\u683C\uFF09", _jsx("input", { type: "number", required: true, min: "0.000001", step: "any", value: instrument.tickSize || '', placeholder: "\u6309\u5408\u7EA6\u586B\u5199", onChange: event => onChange(withInstrument(config, { ...instrument, tickSize: Number(event.target.value) })) })] }), known && !instrument.tickSize && _jsx("p", { className: css.jevInstrumentHint, children: "\u8BE5\u54C1\u79CD\u5C1A\u65E0\u672C\u5730 tick \u53C2\u6570\uFF0C\u8BF7\u6309\u5B9E\u9645\u5408\u7EA6\u89C4\u683C\u586B\u5199\u6700\u5C0F\u4EF7\u683C\u53D8\u52A8\u3002" })] });
    return _jsxs(_Fragment, { children: [_jsxs("label", { children: ["\u641C\u7D22\u671F\u8D27\u54C1\u79CD", _jsx("input", { type: "search", placeholder: "\u540D\u79F0\u3001\u4EE3\u7801\u6216\u4EA4\u6613\u6240", value: search, onChange: event => setSearch(event.target.value) })] }), _jsxs("label", { children: ["\u4EA4\u6613\u54C1\u79CD", _jsxs("select", { value: !known ? 'custom' : instrument.product, onChange: event => {
                            const product = catalog.find(item => item.product === event.target.value);
                            onChange(withInstrument(config, product ? { product: product.product, exchange: product.exchange, tickSize: product.tickSize } : { product: '', exchange: instrument.exchange, tickSize: 0 }));
                        }, children: [Object.entries(exchanges).map(([code, name]) => _jsx("optgroup", { label: name, children: visible.filter(item => item.exchange === code).map(item => _jsxs("option", { value: item.product, disabled: !item.enabled, children: [item.name, " \u00B7 ", item.product.toUpperCase(), item.enabled ? '' : ' · 柜台未启用'] }, item.product)) }, code)), _jsx("option", { value: "custom", children: "\u5176\u4ED6\u54C1\u79CD / \u81EA\u5B9A\u4E49" })] })] }), _jsxs("label", { children: ["\u5B9E\u9645\u5408\u7EA6", _jsx("input", { required: true, pattern: "[a-zA-Z]{1,3}[0-9]{3,4}[fF]?", placeholder: "\u5982 m2701\u3001MA701\u3001l2610F", value: config.symbol, onChange: event => onChange(withSymbol(config, event.target.value.trim(), catalog)) })] }), compact ? _jsxs("details", { className: "qs-instrument-parameters", open: !instrument.tickSize || !known, children: [_jsxs("summary", { children: ["\u5408\u7EA6\u53C2\u6570 \u00B7 ", instrument.exchange, " \u00B7 tick ", instrument.tickSize || '待填写'] }), parameters] }) : parameters] });
}
//# sourceMappingURL=JevInstrument.js.map