import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useRef, useState } from 'react';
import { configuredInstrument, exchanges, products, withInstrument, withSymbol, selectedContracts, withContracts } from "./jev-templates.js";
import { FlyInstrumentContract } from "./fly/FlyInstrumentContract.js";
import css from './ContestPage.module.css';
export function JevInstrument({ config, onChange, catalog = products, quote, accountKey = '' }) {
    const [search, setSearch] = useState('');
    const [exchange, setExchange] = useState('');
    const [manualEntry, setManualEntry] = useState(!config.symbol && !config.contracts?.length);
    const current = useRef(config);
    current.current = config;
    const change = (value) => { current.current = value; onChange(value); };
    const selected = selectedContracts(config, catalog);
    const quoteAccess = useRef();
    if (quote && quoteAccess.current?.query !== quote)
        quoteAccess.current = { query: quote };
    const instrument = configuredInstrument(config, catalog);
    const known = catalog.some(item => item.product === instrument.product);
    const term = search.trim().toLowerCase();
    const visible = catalog.filter(item => (!exchange || item.exchange === exchange) && `${item.name} ${item.product} ${item.exchange} ${exchanges[item.exchange]}`.toLowerCase().includes(term));
    const parameters = _jsxs(_Fragment, { children: [_jsxs("label", { children: ["\u4EA4\u6613\u6240", _jsx("select", { value: instrument.exchange, onChange: event => change(withInstrument(config, { ...instrument, exchange: event.target.value })), children: Object.entries(exchanges).map(([code, name]) => _jsx("option", { value: code, children: name }, code)) })] }), _jsxs("label", { children: ["\u6700\u5C0F\u4EF7\u683C\u53D8\u52A8\uFF08tick \u5BF9\u5E94\u4EF7\u683C\uFF09", _jsx("input", { type: "number", required: true, min: "0.000001", step: "any", value: instrument.tickSize || '', placeholder: "\u6309\u5408\u7EA6\u586B\u5199", onChange: event => change(withInstrument(config, { ...instrument, tickSize: Number(event.target.value) })) })] }), known && !instrument.tickSize && _jsx("p", { className: css.jevInstrumentHint, children: "\u8BE5\u54C1\u79CD\u5C1A\u65E0\u672C\u5730 tick \u53C2\u6570\uFF0C\u8BF7\u6309\u5B9E\u9645\u5408\u7EA6\u89C4\u683C\u586B\u5199\u6700\u5C0F\u4EF7\u683C\u53D8\u52A8\u3002" })] });
    return _jsxs("div", { className: "qs-jev-instruments", children: [_jsxs("details", { className: "qs-instrument-browser", open: true, children: [_jsxs("summary", { children: ["\u52FE\u9009\u671F\u8D27\u54C1\u79CD \u00B7 \u5DF2\u9009 ", selected.length, " \u4E2A"] }), _jsxs("div", { className: "qs-product-filters", children: [_jsxs("label", { children: ["\u641C\u7D22\u671F\u8D27\u54C1\u79CD", _jsx("input", { type: "search", placeholder: "\u540D\u79F0\u3001\u4EE3\u7801\u6216\u4EA4\u6613\u6240", value: search, onChange: event => setSearch(event.target.value) })] }), _jsxs("label", { children: ["\u7B5B\u9009\u4EA4\u6613\u6240", _jsxs("select", { value: exchange, onChange: event => setExchange(event.target.value), children: [_jsx("option", { value: "", children: "\u5168\u90E8\u4EA4\u6613\u6240" }), Object.entries(exchanges).map(([code, name]) => _jsx("option", { value: code, children: name }, code))] })] })] }), _jsxs("div", { className: "qs-product-checklist", "aria-label": "\u53EF\u9009\u671F\u8D27\u54C1\u79CD", children: [visible.map(item => _jsxs("label", { children: [_jsx("input", { type: "checkbox", disabled: !item.enabled, checked: selected.some(value => value.instrument.product === item.product), onChange: event => {
                                            setManualEntry(false);
                                            const entries = selectedContracts(current.current, catalog);
                                            change(withContracts(current.current, event.target.checked ? [...entries, { symbol: '', instrument: { product: item.product, exchange: item.exchange, tickSize: item.tickSize } }] : entries.filter(value => value.instrument.product !== item.product)));
                                        } }), _jsxs("span", { children: [item.name, _jsxs("small", { children: [item.product.toUpperCase(), " \u00B7 ", item.enabled ? item.exchange : '柜台未启用'] })] })] }, item.product)), !visible.length && _jsx("p", { children: "\u6CA1\u6709\u5339\u914D\u54C1\u79CD\uFF0C\u53EF\u5728\u4E0B\u65B9\u624B\u52A8\u586B\u5199\u5408\u7EA6\u3002" })] })] }), _jsxs("div", { className: "qs-selected-contracts", children: [selected.length > 0 && !manualEntry && _jsxs("strong", { children: ["\u5B9E\u9645\u5408\u7EA6 \u00B7 ", selected.length, " \u4E2A\u54C1\u79CD"] }), selected.length && !manualEntry ? selected.map((item, index) => {
                        const name = catalog.find(p => p.product === item.instrument.product)?.name ?? item.instrument.product.toUpperCase();
                        return _jsxs("section", { className: "qs-selected-contract", children: [_jsxs("header", { children: [_jsxs("b", { children: [name, " ", _jsx("small", { children: item.instrument.product.toUpperCase() })] }), _jsx("button", { type: "button", "aria-label": `移除${name}`, onClick: () => change(withContracts(current.current, selectedContracts(current.current, catalog).filter(entry => entry.instrument.product !== item.instrument.product))), children: "\u00D7" })] }), _jsx(FlyInstrumentContract, { product: item.instrument.product, label: name, inputLabel: index === 0 ? '实际合约' : `${name}实际合约`, symbol: item.symbol, invalid: false, contest: quoteAccess.current, accountKey: accountKey, onSymbolChange: (symbol, onlyIfEmpty) => {
                                        if (index === 0 && !onlyIfEmpty) {
                                            change(withSymbol(current.current, symbol, catalog));
                                            return;
                                        }
                                        const entries = selectedContracts(current.current, catalog);
                                        change(withContracts(current.current, entries.map(entry => entry.instrument.product === item.instrument.product && (!onlyIfEmpty || !entry.symbol.trim()) ? { ...entry, symbol } : entry)));
                                    } }), _jsxs("details", { open: !item.instrument.tickSize, children: [_jsxs("summary", { children: ["\u5408\u7EA6\u53C2\u6570 \u00B7 ", item.instrument.exchange, " \u00B7 tick ", item.instrument.tickSize || '待填写'] }), _jsxs("label", { children: [index === 0 ? '最小价格变动（tick 对应价格）' : `${name}最小价格变动`, _jsx("input", { type: "number", min: "0.000001", step: "any", required: true, value: item.instrument.tickSize || '', onChange: event => change(withContracts(current.current, selectedContracts(current.current, catalog).map(entry => entry.instrument.product === item.instrument.product ? { ...entry, instrument: { ...entry.instrument, tickSize: Number(event.target.value) } } : entry))) })] })] })] }, index === 0 ? 'primary' : item.instrument.product);
                    }) : _jsxs("label", { children: ["\u5B9E\u9645\u5408\u7EA6", _jsx("input", { placeholder: "\u4E5F\u53EF\u76F4\u63A5\u586B\u5199\uFF0C\u5982 m2701\u3001MA701", value: config.symbol, onChange: event => change(withSymbol(config, event.target.value.trim(), catalog)) })] }), _jsx("p", { className: "qs-settings-note", children: "\u52FE\u9009\u540E\u8BFB\u53D6\u5F53\u524D\u4E3B\u529B\uFF0C\u4E5F\u53EF\u81EA\u884C\u9009\u62E9\u6708\u4EFD\u6216\u586B\u5199\u5B9E\u9645\u5408\u7EA6\u3002\u5404\u5408\u7EA6\u72EC\u7ACB\u91C7\u6837\u4E0E\u5224\u65AD\uFF0C\u8F6E\u6D41\u67E5\u8BE2\uFF0C\u5171\u7528\u8D26\u6237\u989D\u5EA6\u3002" })] }), _jsxs("details", { className: "qs-instrument-parameters", open: !known || !instrument.tickSize, children: [_jsx("summary", { children: "\u624B\u52A8\u66F4\u6362\u9996\u4E2A\u54C1\u79CD\u4E0E\u4EA4\u6613\u6240" }), _jsxs("label", { children: ["\u4EA4\u6613\u54C1\u79CD", _jsxs("select", { value: !known ? 'custom' : instrument.product, onChange: event => {
                                    const product = catalog.find(item => item.product === event.target.value);
                                    change(withInstrument(config, product ? { product: product.product, exchange: product.exchange, tickSize: product.tickSize } : { product: '', exchange: instrument.exchange, tickSize: 0 }));
                                }, children: [Object.entries(exchanges).map(([code, name]) => _jsx("optgroup", { label: name, children: catalog.filter(item => item.exchange === code).map(item => _jsxs("option", { value: item.product, disabled: !item.enabled, children: [item.name, " \u00B7 ", item.product.toUpperCase(), item.enabled ? '' : ' · 柜台未启用'] }, item.product)) }, code)), _jsx("option", { value: "custom", children: "\u5176\u4ED6\u54C1\u79CD / \u81EA\u5B9A\u4E49" })] })] }), selected.length && !manualEntry ? _jsxs("label", { children: ["\u4EA4\u6613\u6240", _jsx("select", { value: instrument.exchange, onChange: event => change(withInstrument(config, { ...instrument, exchange: event.target.value })), children: Object.entries(exchanges).map(([code, name]) => _jsx("option", { value: code, children: name }, code)) })] }) : parameters] })] });
}
//# sourceMappingURL=JevInstrument.js.map