import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { exchanges, instrumentFor, products, withInstrument, withSymbol } from "./jev-templates.js";
export function JevInstrument({ config, onChange }) {
    const inferred = instrumentFor(config.symbol);
    const instrument = config.instrument ?? { ...inferred, exchange: config.autoHistory?.exchange ?? inferred.exchange, tickSize: config.rangeRules?.tickSize ?? config.signalRules?.tickSize ?? inferred.tickSize };
    const known = products.some(item => item.product === instrument.product);
    return _jsxs(_Fragment, { children: [_jsxs("label", { children: ["\u4EA4\u6613\u54C1\u79CD", _jsxs("select", { value: !known ? 'custom' : instrument.product, onChange: event => {
                            const product = products.find(item => item.product === event.target.value);
                            onChange(withInstrument(config, product ? { product: product.product, exchange: product.exchange, tickSize: product.tickSize } : { product: '', exchange: 'SHF', tickSize: 0 }));
                        }, children: [products.map(item => _jsxs("option", { value: item.product, children: [item.name, " \u00B7 ", item.product.toUpperCase()] }, item.product)), _jsx("option", { value: "custom", children: "\u5176\u4ED6\u54C1\u79CD / \u81EA\u5B9A\u4E49" })] })] }), _jsxs("label", { children: ["\u5B9E\u9645\u5408\u7EA6", _jsx("input", { required: true, pattern: "[a-zA-Z]{1,3}[0-9]{3,4}", placeholder: "\u4F8B\u5982 rb2610\u3001au2612\u3001IF2609", value: config.symbol, onChange: event => onChange(withSymbol(config, event.target.value.trim())) })] }), _jsxs("label", { children: ["\u4EA4\u6613\u6240", _jsx("select", { value: instrument.exchange, onChange: event => onChange(withInstrument(config, { ...instrument, exchange: event.target.value })), children: Object.entries(exchanges).map(([code, name]) => _jsx("option", { value: code, children: name }, code)) })] }), _jsxs("label", { children: ["\u6700\u5C0F\u4EF7\u683C\u53D8\u52A8\uFF08tick \u5BF9\u5E94\u4EF7\u683C\uFF09", _jsx("input", { type: "number", required: true, min: "0.000001", step: "any", value: instrument.tickSize || '', placeholder: "\u6309\u5408\u7EA6\u586B\u5199", onChange: event => onChange(withInstrument(config, { ...instrument, tickSize: Number(event.target.value) })) })] })] });
}
//# sourceMappingURL=JevInstrument.js.map