/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { QuantSkillsApplicationUpdateCheckRequest, QuantSkillsApplicationUpdateStartResult, QuantSkillsApplicationUpdateStatus, QuantSkillsAssetReadme, QuantSkillsAssetReadmeRequest, QuantSkillsCatalogSnapshot, QuantSkillsCatalogSyncStatus, QuantSkillsInstalledAgentTemplate, QuantSkillsInstalledSnapshot, QuantSkillsInstalledVersion, QuantSkillsInstalledVersionId, QuantSkillsInstallRequest, QuantSkillsManualSkillSaveRequest } from '@deepseek-ai/dsh-quantskills-host/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7175616e74536b696c6c73 {
    agentTemplate: (versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledAgentTemplate>>
    applicationUpdateCheck: (request: QuantSkillsApplicationUpdateCheckRequest) => Promise<RemoteResult<QuantSkillsApplicationUpdateStartResult>>
    applicationUpdateStart: () => Promise<RemoteResult<QuantSkillsApplicationUpdateStartResult>>
    applicationUpdateStatus: () => Promise<RemoteResult<QuantSkillsApplicationUpdateStatus>>
    assetReadme: (request: QuantSkillsAssetReadmeRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAssetReadme>>
    catalog: (signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsCatalogSnapshot>>
    catalogSyncStatus: () => Promise<RemoteResult<QuantSkillsCatalogSyncStatus>>
    installAsset: (request: QuantSkillsInstallRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledVersion>>
    list: (signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledSnapshot>>
    manualSkillRead: (versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal) => Promise<RemoteResult<string>>
    manualSkillSave: (request: QuantSkillsManualSkillSaveRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledVersion>>
    uninstallAsset: (request: { readonly assetId: string; }, signal?: AbortSignal) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteMap {
    'quantSkills/agentTemplate': (versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledAgentTemplate>>
    'quantSkills/applicationUpdateCheck': (request: QuantSkillsApplicationUpdateCheckRequest) => Promise<RemoteResult<QuantSkillsApplicationUpdateStartResult>>
    'quantSkills/applicationUpdateStart': () => Promise<RemoteResult<QuantSkillsApplicationUpdateStartResult>>
    'quantSkills/applicationUpdateStatus': () => Promise<RemoteResult<QuantSkillsApplicationUpdateStatus>>
    'quantSkills/assetReadme': (request: QuantSkillsAssetReadmeRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsAssetReadme>>
    'quantSkills/catalog': (signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsCatalogSnapshot>>
    'quantSkills/catalogSyncStatus': () => Promise<RemoteResult<QuantSkillsCatalogSyncStatus>>
    'quantSkills/installAsset': (request: QuantSkillsInstallRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledVersion>>
    'quantSkills/list': (signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledSnapshot>>
    'quantSkills/manualSkillRead': (versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal) => Promise<RemoteResult<string>>
    'quantSkills/manualSkillSave': (request: QuantSkillsManualSkillSaveRequest, signal?: AbortSignal) => Promise<RemoteResult<QuantSkillsInstalledVersion>>
    'quantSkills/uninstallAsset': (request: { readonly assetId: string; }, signal?: AbortSignal) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteNamespaceMap {
    'quantSkills': TypertRemoteNamespace$7175616e74536b696c6c73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
