/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_quantskills_host_quantSkills_agentTemplate_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_quantskills_host_quantSkills_agentTemplate_result$schema = z.object({
  'version': z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("skill"), z.literal("agent")]).readonly(),
  'repository': z.string().readonly(),
  'commit': z.intersection(z.string(), z.unknown()).readonly(),
  'declaration': z.union([z.literal("SKILL.md"), z.literal("AGENTS.md")]).readonly(),
  'treeDigest': z.intersection(z.string(), z.unknown()).readonly(),
  'fileCount': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'installedAt': z.number().readonly(),
  'exposure': z.union([z.literal("skill-registry"), z.literal("agent-template")]).readonly(),
  'origin': z.union([z.literal("catalog"), z.literal("local-authoring")]).readonly(),
  'declarationTitleZh': z.string().readonly().optional(),
}).readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'instructions': z.string().readonly(),
  'requires': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'promptForm': z.union([z.object({
  'status': z.literal("ready").readonly(),
  'form': z.object({
  'version': z.literal(1).readonly(),
  'task': z.object({
  'placeholder': z.string().readonly().optional(),
  'required': z.boolean().readonly().optional(),
}).readonly().optional(),
  'fields': z.array(z.object({
  'key': z.string().readonly(),
  'label': z.string().readonly(),
  'type': z.union([z.literal("number"), z.literal("text"), z.literal("textarea"), z.literal("select"), z.literal("date")]).readonly(),
  'required': z.boolean().readonly().optional(),
  'placeholder': z.string().readonly().optional(),
  'help': z.string().readonly().optional(),
  'default': z.union([z.string(), z.number()]).readonly().optional(),
  'options': z.array(z.object({
  'value': z.string().readonly(),
  'label': z.string().readonly(),
})).readonly().optional(),
})).readonly(),
  'promptTemplate': z.string().readonly(),
}).readonly(),
  'adaptations': z.array(z.object({
  'code': z.literal("number-default-string").readonly(),
  'fieldKey': z.string().readonly(),
})).readonly().optional(),
}), z.object({
  'status': z.literal("invalid").readonly(),
  'reason': z.string().readonly(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateCheck_parameter_0$schema = z.object({
  'source': z.union([z.literal("github"), z.literal("gitee")]).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateCheck_result$schema = z.object({
  'accepted': z.union([z.literal("started"), z.literal("reused")]).readonly(),
  'status': z.object({
  'state': z.union([z.literal("idle"), z.literal("checking"), z.literal("current"), z.literal("available"), z.literal("preparing"), z.literal("ready"), z.literal("blocked"), z.literal("failed")]).readonly(),
  'source': z.union([z.literal("github"), z.literal("gitee")]).readonly().optional(),
  'currentVersion': z.string().readonly().optional(),
  'currentCommit': z.string().readonly().optional(),
  'candidateVersion': z.string().readonly().optional(),
  'candidateCommit': z.string().readonly().optional(),
  'releaseNotes': z.array(z.string()).readonly().optional(),
  'phase': z.union([z.literal("fetching"), z.literal("installing"), z.literal("verifying")]).readonly().optional(),
  'checkedAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("CATALOG_FETCH_FAILED"), z.literal("CATALOG_INVALID"), z.literal("CATALOG_STALE"), z.literal("ASSET_NOT_FOUND"), z.literal("ASSET_README_FETCH_FAILED"), z.literal("ASSET_README_NOT_FOUND"), z.literal("ASSET_README_INVALID"), z.literal("INSTALL_INVALID_TREE"), z.literal("INSTALL_LIMIT_EXCEEDED"), z.literal("INSTALL_GIT_FAILED"), z.literal("INSTALL_EXPOSURE_FAILED"), z.literal("INSTALL_RECORD_CORRUPT"), z.literal("INSTALL_WRITE_FAILED"), z.literal("INSTALLED_VERSION_NOT_FOUND"), z.literal("INSTALLED_VERSION_NOT_SKILL"), z.literal("INSTALLED_VERSION_NOT_AGENT"), z.literal("APPLICATION_UPDATE_CHECK_FAILED"), z.literal("APPLICATION_UPDATE_NOT_AVAILABLE"), z.literal("APPLICATION_UPDATE_DOWNLOAD_FAILED"), z.literal("APPLICATION_UPDATE_INSTALL_FAILED"), z.literal("APPLICATION_UPDATE_VERIFY_FAILED"), z.literal("APPLICATION_UPDATE_STATE_CORRUPT"), z.literal("APPLICATION_UPDATE_PATH_INVALID"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_DIRTY"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_REMOTE"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_BRANCH"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_AHEAD"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_DIVERGED")]).readonly().optional(),
}).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateStart_result$schema = z.object({
  'accepted': z.union([z.literal("started"), z.literal("reused")]).readonly(),
  'status': z.object({
  'state': z.union([z.literal("idle"), z.literal("checking"), z.literal("current"), z.literal("available"), z.literal("preparing"), z.literal("ready"), z.literal("blocked"), z.literal("failed")]).readonly(),
  'source': z.union([z.literal("github"), z.literal("gitee")]).readonly().optional(),
  'currentVersion': z.string().readonly().optional(),
  'currentCommit': z.string().readonly().optional(),
  'candidateVersion': z.string().readonly().optional(),
  'candidateCommit': z.string().readonly().optional(),
  'releaseNotes': z.array(z.string()).readonly().optional(),
  'phase': z.union([z.literal("fetching"), z.literal("installing"), z.literal("verifying")]).readonly().optional(),
  'checkedAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("CATALOG_FETCH_FAILED"), z.literal("CATALOG_INVALID"), z.literal("CATALOG_STALE"), z.literal("ASSET_NOT_FOUND"), z.literal("ASSET_README_FETCH_FAILED"), z.literal("ASSET_README_NOT_FOUND"), z.literal("ASSET_README_INVALID"), z.literal("INSTALL_INVALID_TREE"), z.literal("INSTALL_LIMIT_EXCEEDED"), z.literal("INSTALL_GIT_FAILED"), z.literal("INSTALL_EXPOSURE_FAILED"), z.literal("INSTALL_RECORD_CORRUPT"), z.literal("INSTALL_WRITE_FAILED"), z.literal("INSTALLED_VERSION_NOT_FOUND"), z.literal("INSTALLED_VERSION_NOT_SKILL"), z.literal("INSTALLED_VERSION_NOT_AGENT"), z.literal("APPLICATION_UPDATE_CHECK_FAILED"), z.literal("APPLICATION_UPDATE_NOT_AVAILABLE"), z.literal("APPLICATION_UPDATE_DOWNLOAD_FAILED"), z.literal("APPLICATION_UPDATE_INSTALL_FAILED"), z.literal("APPLICATION_UPDATE_VERIFY_FAILED"), z.literal("APPLICATION_UPDATE_STATE_CORRUPT"), z.literal("APPLICATION_UPDATE_PATH_INVALID"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_DIRTY"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_REMOTE"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_BRANCH"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_AHEAD"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_DIVERGED")]).readonly().optional(),
}).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateStatus_result$schema = z.object({
  'state': z.union([z.literal("idle"), z.literal("checking"), z.literal("current"), z.literal("available"), z.literal("preparing"), z.literal("ready"), z.literal("blocked"), z.literal("failed")]).readonly(),
  'source': z.union([z.literal("github"), z.literal("gitee")]).readonly().optional(),
  'currentVersion': z.string().readonly().optional(),
  'currentCommit': z.string().readonly().optional(),
  'candidateVersion': z.string().readonly().optional(),
  'candidateCommit': z.string().readonly().optional(),
  'releaseNotes': z.array(z.string()).readonly().optional(),
  'phase': z.union([z.literal("fetching"), z.literal("installing"), z.literal("verifying")]).readonly().optional(),
  'checkedAt': z.number().readonly().optional(),
  'errorCode': z.union([z.literal("CATALOG_FETCH_FAILED"), z.literal("CATALOG_INVALID"), z.literal("CATALOG_STALE"), z.literal("ASSET_NOT_FOUND"), z.literal("ASSET_README_FETCH_FAILED"), z.literal("ASSET_README_NOT_FOUND"), z.literal("ASSET_README_INVALID"), z.literal("INSTALL_INVALID_TREE"), z.literal("INSTALL_LIMIT_EXCEEDED"), z.literal("INSTALL_GIT_FAILED"), z.literal("INSTALL_EXPOSURE_FAILED"), z.literal("INSTALL_RECORD_CORRUPT"), z.literal("INSTALL_WRITE_FAILED"), z.literal("INSTALLED_VERSION_NOT_FOUND"), z.literal("INSTALLED_VERSION_NOT_SKILL"), z.literal("INSTALLED_VERSION_NOT_AGENT"), z.literal("APPLICATION_UPDATE_CHECK_FAILED"), z.literal("APPLICATION_UPDATE_NOT_AVAILABLE"), z.literal("APPLICATION_UPDATE_DOWNLOAD_FAILED"), z.literal("APPLICATION_UPDATE_INSTALL_FAILED"), z.literal("APPLICATION_UPDATE_VERIFY_FAILED"), z.literal("APPLICATION_UPDATE_STATE_CORRUPT"), z.literal("APPLICATION_UPDATE_PATH_INVALID"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_DIRTY"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_REMOTE"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_BRANCH"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_AHEAD"), z.literal("APPLICATION_UPDATE_DEVELOPMENT_DIVERGED")]).readonly().optional(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_assetReadme_parameter_0$schema = z.object({
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'observedSnapshotId': z.intersection(z.string(), z.unknown()).readonly(),
  'observedCommit': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_assetReadme_result$schema = z.object({
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'commit': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.union([z.literal("SKILL.md"), z.literal("README.md")]).readonly(),
  'markdown': z.string().readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_catalog_result$schema = z.object({
  'snapshotId': z.intersection(z.string(), z.unknown()).readonly(),
  'refreshAfterMs': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.string().readonly(),
  'labelEn': z.string().readonly(),
  'labelZh': z.string().readonly(),
  'subcategories': z.array(z.object({
  'id': z.string().readonly(),
  'labelEn': z.string().readonly(),
  'labelZh': z.string().readonly(),
})).readonly(),
})).readonly(),
  'assets': z.array(z.object({
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("skill"), z.literal("agent")]).readonly(),
  'repository': z.string().readonly(),
  'commit': z.intersection(z.string(), z.unknown()).readonly(),
  'declaration': z.union([z.literal("SKILL.md"), z.literal("AGENTS.md")]).readonly(),
  'displayNames': z.object({
  'zhCN': z.string().readonly(),
  'en': z.string().readonly().optional(),
}).readonly(),
  'aliases': z.array(z.string()).readonly(),
  'nameSource': z.union([z.literal("catalog"), z.literal("declaration"), z.literal("generated"), z.literal("asset-id")]).readonly(),
  'title': z.string().readonly().optional(),
  'category': z.string().readonly().optional(),
  'subcategory': z.string().readonly().optional(),
  'description': z.string().readonly().optional(),
  'health': z.string().readonly().optional(),
  'validationLevel': z.string().readonly().optional(),
  'requires': z.array(z.intersection(z.string(), z.unknown())).readonly().optional(),
  'summaryEn': z.string().readonly().optional(),
  'summaryZh': z.string().readonly().optional(),
})).readonly(),
  'sync': z.object({
  'mode': z.union([z.literal("manual"), z.literal("event-stream")]).readonly(),
  'state': z.union([z.literal("connected"), z.literal("error"), z.literal("idle"), z.literal("connecting"), z.literal("reconnecting")]).readonly(),
  'connectedAt': z.number().readonly().optional(),
  'eventReceivedAt': z.number().readonly().optional(),
  'error': z.string().readonly().optional(),
}).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_catalogSyncStatus_result$schema = z.object({
  'mode': z.union([z.literal("manual"), z.literal("event-stream")]).readonly(),
  'state': z.union([z.literal("connected"), z.literal("error"), z.literal("idle"), z.literal("connecting"), z.literal("reconnecting")]).readonly(),
  'connectedAt': z.number().readonly().optional(),
  'eventReceivedAt': z.number().readonly().optional(),
  'error': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_installAsset_parameter_0$schema = z.object({
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'observedSnapshotId': z.intersection(z.string(), z.unknown()).readonly(),
  'observedCommit': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_installAsset_result$schema = z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("skill"), z.literal("agent")]).readonly(),
  'repository': z.string().readonly(),
  'commit': z.intersection(z.string(), z.unknown()).readonly(),
  'declaration': z.union([z.literal("SKILL.md"), z.literal("AGENTS.md")]).readonly(),
  'treeDigest': z.intersection(z.string(), z.unknown()).readonly(),
  'fileCount': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'installedAt': z.number().readonly(),
  'exposure': z.union([z.literal("skill-registry"), z.literal("agent-template")]).readonly(),
  'origin': z.union([z.literal("catalog"), z.literal("local-authoring")]).readonly(),
  'declarationTitleZh': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_list_result$schema = z.object({
  'versions': z.array(z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("skill"), z.literal("agent")]).readonly(),
  'repository': z.string().readonly(),
  'commit': z.intersection(z.string(), z.unknown()).readonly(),
  'declaration': z.union([z.literal("SKILL.md"), z.literal("AGENTS.md")]).readonly(),
  'treeDigest': z.intersection(z.string(), z.unknown()).readonly(),
  'fileCount': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'installedAt': z.number().readonly(),
  'exposure': z.union([z.literal("skill-registry"), z.literal("agent-template")]).readonly(),
  'origin': z.union([z.literal("catalog"), z.literal("local-authoring")]).readonly(),
  'declarationTitleZh': z.string().readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillRead_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillRead_result$schema = z.string()
const _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillSave_parameter_0$schema = z.object({
  'markdown': z.string().readonly(),
  'mode': z.union([z.literal("create"), z.literal("edit"), z.literal("copy")]).readonly(),
  'sourceVersionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'copyAssetId': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillSave_result$schema = z.object({
  'versionId': z.intersection(z.string(), z.unknown()).readonly(),
  'assetId': z.intersection(z.string(), z.unknown()).readonly(),
  'kind': z.union([z.literal("skill"), z.literal("agent")]).readonly(),
  'repository': z.string().readonly(),
  'commit': z.intersection(z.string(), z.unknown()).readonly(),
  'declaration': z.union([z.literal("SKILL.md"), z.literal("AGENTS.md")]).readonly(),
  'treeDigest': z.intersection(z.string(), z.unknown()).readonly(),
  'fileCount': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'installedAt': z.number().readonly(),
  'exposure': z.union([z.literal("skill-registry"), z.literal("agent-template")]).readonly(),
  'origin': z.union([z.literal("catalog"), z.literal("local-authoring")]).readonly(),
  'declarationTitleZh': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_uninstallAsset_parameter_0$schema = z.object({
  'assetId': z.string().readonly(),
})
const _deepseek_ai_dsh_quantskills_host_quantSkills_uninstallAsset_result$schema = z.void()

export const TYPERT = {
  package: '@deepseek-ai/dsh-quantskills-host',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/agentTemplate',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'agentTemplate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'versionId',
          wire: 'versionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstalledVersionId',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_agentTemplate_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstalledAgentTemplate',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_agentTemplate_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":680,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/applicationUpdateCheck',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'applicationUpdateCheck',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsApplicationUpdateCheckRequest',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateCheck_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsApplicationUpdateStartResult',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateCheck_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":549,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/applicationUpdateStart',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'applicationUpdateStart',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsApplicationUpdateStartResult',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateStart_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":558,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/applicationUpdateStatus',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'applicationUpdateStatus',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsApplicationUpdateStatus',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_applicationUpdateStatus_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":539,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/assetReadme',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'assetReadme',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsAssetReadmeRequest',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_assetReadme_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsAssetReadme',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_assetReadme_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":569,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/catalog',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'catalog',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsCatalogSnapshot',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_catalog_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":487,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/catalogSyncStatus',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'catalogSyncStatus',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsCatalogSyncStatus',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_catalogSyncStatus_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":503,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/installAsset',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'installAsset',
      implementation: 'install',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstallRequest',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_installAsset_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstalledVersion',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_installAsset_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":584,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/list',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstalledSnapshot',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_list_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":513,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/manualSkillRead',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'manualSkillRead',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'versionId',
          wire: 'versionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstalledVersionId',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillRead_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host#quantSkills/manualSkillRead:result',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillRead_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":787,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/manualSkillSave',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'manualSkillSave',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsManualSkillSaveRequest',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillSave_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host/types#QuantSkillsInstalledVersion',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_manualSkillSave_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":798,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-quantskills-host#quantSkills/uninstallAsset',
      service: 'quantSkillsHost',
      namespace: 'quantSkills',
      method: 'uninstallAsset',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-quantskills-host#quantSkills/uninstallAsset:request',
            schema: _deepseek_ai_dsh_quantskills_host_quantSkills_uninstallAsset_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-quantskills-host#quantSkills/uninstallAsset:result',
        schema: _deepseek_ai_dsh_quantskills_host_quantSkills_uninstallAsset_result$schema,
      },
      sourceLocation: {"file":"packages/quantskills-host/src/index.ts","line":519,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote Host service that owns catalog freshness checks and installed-version truth.",
        "summary": "Remote Host service that owns catalog freshness checks and installed-version truth.",
        "tags": [],
        "jsDoc": "/** Remote Host service that owns catalog freshness checks and installed-version truth. */",
        "key": "quantSkillsHost",
        "exportName": "QuantSkillsHostGateway",
        "members": [
          {
            "kind": "method",
            "name": "catalog",
            "signature": "@Remote('catalog') catalog(signal?: AbortSignal): Promise<QuantSkillsCatalogSnapshot>",
            "summary": "Read the approved official catalog without making a validated process cache wait on GitHub.",
            "jsDoc": "/**\r\n * Read the approved official catalog without making a validated process cache wait on GitHub.\r\n * @param signal - optional caller cancellation for the initial or background fetch.\r\n * @returns a bounded, validated point-in-time snapshot.\r\n */"
          },
          {
            "kind": "method",
            "name": "catalogSyncStatus",
            "signature": "@Remote('catalogSyncStatus') catalogSyncStatus(): QuantSkillsCatalogSyncStatus",
            "summary": "Read the current event-driven catalog delivery state.",
            "jsDoc": "/**\r\n * Read the current event-driven catalog delivery state.\r\n * @returns Host-owned connection state for the configured relay.\r\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(signal?: AbortSignal): Promise<QuantSkillsInstalledSnapshot>",
            "summary": "List versions with a complete Host publication record.",
            "jsDoc": "/**\r\n * List versions with a complete Host publication record.\r\n * @param signal - optional caller cancellation.\r\n * @returns immutable installed versions sorted by asset and commit.\r\n */"
          },
          {
            "kind": "method",
            "name": "uninstallAsset",
            "signature": "@Remote('uninstallAsset') uninstallAsset(request: { readonly assetId: string }, signal?: AbortSignal): Promise<void>",
            "summary": "Remove a catalog asset from discovery while retaining immutable versions for existing sessions.",
            "jsDoc": "/** Remove a catalog asset from discovery while retaining immutable versions for existing sessions. */"
          },
          {
            "kind": "method",
            "name": "applicationUpdateStatus",
            "signature": "@Remote('applicationUpdateStatus') applicationUpdateStatus(): QuantSkillsApplicationUpdateStatus",
            "jsDoc": "/** @returns the current background application-update state without network I/O. */"
          },
          {
            "kind": "method",
            "name": "applicationUpdateCheck",
            "signature": "@Remote('applicationUpdateCheck') applicationUpdateCheck(request: QuantSkillsApplicationUpdateCheckRequest): QuantSkillsApplicationUpdateStartResult",
            "summary": "Start a user-requested official version check without downloading an update.",
            "jsDoc": "/**\r\n * Start a user-requested official version check without downloading an update.\r\n * @param request - explicit Git service selected by the user.\r\n * @returns immediate started-or-reused acknowledgement.\r\n */"
          },
          {
            "kind": "method",
            "name": "applicationUpdateStart",
            "signature": "@Remote('applicationUpdateStart') applicationUpdateStart(): QuantSkillsApplicationUpdateStartResult",
            "summary": "Prepare the version selected by the user's latest completed check.",
            "jsDoc": "/**\r\n * Prepare the version selected by the user's latest completed check.\r\n * @returns immediate started-or-reused acknowledgement.\r\n */"
          },
          {
            "kind": "method",
            "name": "assetReadme",
            "signature": "@Remote('assetReadme') assetReadme( request: QuantSkillsAssetReadmeRequest, signal?: AbortSignal, ): Promise<QuantSkillsAssetReadme>",
            "summary": "Read the repository's real README at the exact commit shown by the Client.",
            "jsDoc": "/**\r\n * Read the repository's real README at the exact commit shown by the Client.\r\n * @param request - catalog-bound asset identity and exact observed commit.\r\n * @param signal - optional caller cancellation propagated to both catalog and README fetches.\r\n * @returns bounded UTF-8 Markdown from the approved repository version.\r\n */"
          },
          {
            "kind": "method",
            "name": "install",
            "signature": "@Remote('installAsset') install(request: QuantSkillsInstallRequest, signal?: AbortSignal): Promise<QuantSkillsInstalledVersion>",
            "summary": "Re-fetch the catalog, enforce the Client's observed snapshot and commit, and atomically publish one validated immutable version.",
            "jsDoc": "/**\r\n * Re-fetch the catalog, enforce the Client's observed snapshot and commit,\r\n * and atomically publish one validated immutable version.\r\n * @param request - catalog-bound asset identity and exact observed commit.\r\n * @param signal - optional caller cancellation propagated to fetch and Git.\r\n * @returns the Host-committed installation record.\r\n */"
          },
          {
            "kind": "method",
            "name": "resolveInstalledSkill",
            "signature": "resolveInstalledSkill( versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal, ): Promise<QuantSkillsResolvedInstalledSkill>",
            "summary": "Resolve one exact installed Skill for a session-scoped provider.",
            "jsDoc": "/**\r\n * Resolve one exact installed Skill for a session-scoped provider.\r\n * @param versionId - Host-issued immutable installed-version identity.\r\n * @param signal - optional caller cancellation.\r\n * @returns the validated manifest and complete exact-version definition.\r\n * @throws when the version is absent, stored-only, or corrupt.\r\n */"
          },
          {
            "kind": "method",
            "name": "resolveInstalledResource",
            "signature": "resolveInstalledResource( versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal, ): Promise<Readonly<{ version: QuantSkillsInstalledVersion; resourceBase: string }>>",
            "summary": "Resolve the immutable source directory for one exact installed version.",
            "jsDoc": "/**\r\n * Resolve the immutable source directory for one exact installed version.\r\n * This same-process Host method lets trusted consumers authorize legacy files without\r\n * projecting the Host filesystem path through the remote Agent-template response.\r\n * @param versionId - Host-issued immutable installed-version identity.\r\n * @param signal - optional caller cancellation.\r\n * @returns the validated public manifest and its immutable source directory.\r\n */"
          },
          {
            "kind": "method",
            "name": "matchInstalledSkillResource",
            "signature": "matchInstalledSkillResource( resourceBase: string, signal?: AbortSignal, ): Promise<Readonly<{ version: QuantSkillsInstalledVersion; resourceBase: string }> | undefined>",
            "summary": "Match one model-visible resource directory to an exact installed registry Skill.",
            "jsDoc": "/**\r\n * Match one model-visible resource directory to an exact installed registry Skill.\r\n * This same-process lookup lets trusted Session consumers validate durable `skill`\r\n * tool results without exposing the installed-version root through RPC.\r\n * @param resourceBase - directory rendered by the successful Skill tool result.\r\n * @param signal - optional caller cancellation.\r\n * @returns the exact Skill manifest and source directory, or undefined when no installation matches.\r\n */"
          },
          {
            "kind": "method",
            "name": "agentTemplate",
            "signature": "@Remote('agentTemplate') agentTemplate( versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal, ): Promise<QuantSkillsInstalledAgentTemplate>",
            "summary": "Resolve one exact installed Agent as an editable user-Agent template.",
            "jsDoc": "/**\r\n * Resolve one exact installed Agent as an editable user-Agent template.\r\n * @param versionId - Host-issued immutable installed-version identity.\r\n * @param signal - optional caller cancellation.\r\n * @returns validated Agent metadata, instructions, and exact dependency identities.\r\n */"
          },
          {
            "kind": "method",
            "name": "prepareAuthoredDraft",
            "signature": "async prepareAuthoredDraft( request: QuantSkillsAuthoredDraftPrepareRequest, signal?: AbortSignal, ): Promise<QuantSkillsAuthoredDraft>",
            "summary": "Validate one Workspace-local authoring draft through the same Git-tree admission used by catalog installs.",
            "jsDoc": "/**\r\n * Validate one Workspace-local authoring draft through the same Git-tree admission used by catalog installs.\r\n * @param request - draft directory and declaration family.\r\n * @param signal - optional caller cancellation.\r\n * @returns content identity and validated declaration metadata without publishing files.\r\n */"
          },
          {
            "kind": "method",
            "name": "publishAuthoredDraft",
            "signature": "async publishAuthoredDraft( request: QuantSkillsAuthoredDraftPublishRequest, signal?: AbortSignal, ): Promise<QuantSkillsInstalledVersion>"
          },
          {
            "kind": "method",
            "name": "manualSkillRead",
            "signature": "@Remote('manualSkillRead') async manualSkillRead(versionId: QuantSkillsInstalledVersionId, signal?: AbortSignal): Promise<string>",
            "summary": "Save a manual declaration through the same admission and immutable publication as AI creation.",
            "jsDoc": "/** Save a manual declaration through the same admission and immutable publication as AI creation. */"
          },
          {
            "kind": "method",
            "name": "manualSkillSave",
            "signature": "@Remote('manualSkillSave') manualSkillSave(request: QuantSkillsManualSkillSaveRequest, signal?: AbortSignal): Promise<QuantSkillsInstalledVersion>"
          }
        ],
        "types": [
          {
            "name": "QuantSkillsApplicationUpdateCheckRequest",
            "declaration": "export interface QuantSkillsApplicationUpdateCheckRequest {\n    readonly source: QuantSkillsApplicationUpdateSource;\n}"
          },
          {
            "name": "QuantSkillsApplicationUpdatePhase",
            "declaration": "export type QuantSkillsApplicationUpdatePhase = 'fetching' | 'installing' | 'verifying';"
          },
          {
            "name": "QuantSkillsApplicationUpdateSource",
            "declaration": "export type QuantSkillsApplicationUpdateSource = 'github' | 'gitee';"
          },
          {
            "name": "QuantSkillsApplicationUpdateStartResult",
            "declaration": "export interface QuantSkillsApplicationUpdateStartResult {\n    readonly accepted: 'started' | 'reused';\n    readonly status: QuantSkillsApplicationUpdateStatus;\n}"
          },
          {
            "name": "QuantSkillsApplicationUpdateState",
            "declaration": "export type QuantSkillsApplicationUpdateState = 'idle' | 'checking' | 'current' | 'available' | 'preparing' | 'ready' | 'blocked' | 'failed';"
          },
          {
            "name": "QuantSkillsApplicationUpdateStatus",
            "declaration": "export interface QuantSkillsApplicationUpdateStatus {\n    readonly state: QuantSkillsApplicationUpdateState;\n    readonly source?: QuantSkillsApplicationUpdateSource;\n    readonly currentVersion?: string;\n    readonly currentCommit?: string;\n    readonly candidateVersion?: string;\n    readonly candidateCommit?: string;\n    readonly releaseNotes?: readonly string[];\n    readonly phase?: QuantSkillsApplicationUpdatePhase;\n    readonly checkedAt?: number;\n    readonly errorCode?: QuantSkillsHostErrorCode;\n}"
          },
          {
            "name": "QuantSkillsAssetId",
            "declaration": "export type QuantSkillsAssetId = Branded<'QuantSkillsAssetId'>;"
          },
          {
            "name": "QuantSkillsAssetKind",
            "declaration": "export type QuantSkillsAssetKind = 'skill' | 'agent';"
          },
          {
            "name": "QuantSkillsAssetReadme",
            "declaration": "export interface QuantSkillsAssetReadme {\n    readonly assetId: QuantSkillsAssetId;\n    readonly commit: QuantSkillsCommitSha;\n    readonly path: 'README.md' | 'SKILL.md';\n    readonly markdown: string;\n}"
          },
          {
            "name": "QuantSkillsAssetReadmeRequest",
            "declaration": "export interface QuantSkillsAssetReadmeRequest {\n    readonly assetId: QuantSkillsAssetId;\n    readonly observedSnapshotId: QuantSkillsSnapshotId;\n    readonly observedCommit: QuantSkillsCommitSha;\n}"
          },
          {
            "name": "QuantSkillsAuthoredDraft",
            "declaration": "export interface QuantSkillsAuthoredDraft {\n    readonly assetId: QuantSkillsAssetId;\n    readonly kind: QuantSkillsAssetKind;\n    readonly declaration: QuantSkillsDeclarationFile;\n    readonly treeDigest: QuantSkillsTreeDigest;\n    readonly fileCount: number;\n    readonly totalBytes: number;\n    readonly requires: readonly QuantSkillsAssetId[];\n}"
          },
          {
            "name": "QuantSkillsAuthoredDraftPrepareRequest",
            "declaration": "export interface QuantSkillsAuthoredDraftPrepareRequest {\n    readonly draftRoot: string;\n    readonly kind: QuantSkillsAssetKind;\n}"
          },
          {
            "name": "QuantSkillsAuthoredDraftPublishRequest",
            "declaration": "export interface QuantSkillsAuthoredDraftPublishRequest extends QuantSkillsAuthoredDraftPrepareRequest {\n    readonly expectedTreeDigest: QuantSkillsTreeDigest;\n    readonly expectedBaseVersionId?: QuantSkillsInstalledVersionId | null;\n}"
          },
          {
            "name": "QuantSkillsCatalogAsset",
            "declaration": "export interface QuantSkillsCatalogAsset {\n    readonly assetId: QuantSkillsAssetId;\n    readonly kind: QuantSkillsAssetKind;\n    readonly repository: string;\n    readonly commit: QuantSkillsCommitSha;\n    readonly declaration: QuantSkillsDeclarationFile;\n    readonly displayNames: QuantSkillsDisplayNames;\n    readonly aliases: readonly string[];\n    readonly nameSource: QuantSkillsDisplayNameSource;\n    readonly title?: string;\n    readonly category?: string;\n    readonly subcategory?: string;\n    readonly description?: string;\n    readonly health?: string;\n    readonly validationLevel?: string;\n    readonly requires?: readonly QuantSkillsAssetId[];\n    readonly summaryEn?: string;\n    readonly summaryZh?: string;\n}"
          },
          {
            "name": "QuantSkillsCatalogCategory",
            "declaration": "export interface QuantSkillsCatalogCategory {\n    readonly id: string;\n    readonly labelEn: string;\n    readonly labelZh: string;\n    readonly subcategories: readonly QuantSkillsCatalogSubcategory[];\n}"
          },
          {
            "name": "QuantSkillsCatalogSnapshot",
            "declaration": "export interface QuantSkillsCatalogSnapshot {\n    readonly snapshotId: QuantSkillsSnapshotId;\n    readonly refreshAfterMs: number;\n    readonly categories: readonly QuantSkillsCatalogCategory[];\n    readonly assets: readonly QuantSkillsCatalogAsset[];\n    readonly sync: QuantSkillsCatalogSyncStatus;\n}"
          },
          {
            "name": "QuantSkillsCatalogSubcategory",
            "declaration": "export interface QuantSkillsCatalogSubcategory {\n    readonly id: string;\n    readonly labelEn: string;\n    readonly labelZh: string;\n}"
          },
          {
            "name": "QuantSkillsCatalogSyncStatus",
            "declaration": "export interface QuantSkillsCatalogSyncStatus {\n    readonly mode: 'manual' | 'event-stream';\n    readonly state: 'idle' | 'connecting' | 'connected' | 'reconnecting' | 'error';\n    readonly connectedAt?: number;\n    readonly eventReceivedAt?: number;\n    readonly error?: string;\n}"
          },
          {
            "name": "QuantSkillsCommitSha",
            "declaration": "export type QuantSkillsCommitSha = Branded<'QuantSkillsCommitSha'>;"
          },
          {
            "name": "QuantSkillsDeclarationFile",
            "declaration": "export type QuantSkillsDeclarationFile = 'SKILL.md' | 'AGENTS.md';"
          },
          {
            "name": "QuantSkillsDisplayNames",
            "declaration": "export interface QuantSkillsDisplayNames {\n    readonly zhCN: string;\n    readonly en?: string;\n}"
          },
          {
            "name": "QuantSkillsDisplayNameSource",
            "declaration": "export type QuantSkillsDisplayNameSource = 'catalog' | 'declaration' | 'generated' | 'asset-id';"
          },
          {
            "name": "QuantSkillsHostErrorCode",
            "declaration": "export type QuantSkillsHostErrorCode = 'CATALOG_FETCH_FAILED' | 'CATALOG_INVALID' | 'CATALOG_STALE' | 'ASSET_NOT_FOUND' | 'ASSET_README_FETCH_FAILED' | 'ASSET_README_NOT_FOUND' | 'ASSET_README_INVALID' | 'INSTALL_INVALID_TREE' | 'INSTALL_LIMIT_EXCEEDED' | 'INSTALL_GIT_FAILED' | 'INSTALL_EXPOSURE_FAILED' | 'INSTALL_RECORD_CORRUPT' | 'INSTALL_WRITE_FAILED' | 'INSTALLED_VERSION_NOT_FOUND' | 'INSTALLED_VERSION_NOT_SKILL' | 'INSTALLED_VERSION_NOT_AGENT' | 'APPLICATION_UPDATE_CHECK_FAILED' | 'APPLICATION_UPDATE_NOT_AVAILABLE' | 'APPLICATION_UPDATE_DOWNLOAD_FAILED' | 'APPLICATION_UPDATE_INSTALL_FAILED' | 'APPLICATION_UPDATE_VERIFY_FAILED' | 'APPLICATION_UPDATE_STATE_CORRUPT' | 'APPLICATION_UPDATE_PATH_INVALID' | 'APPLICATION_UPDATE_DEVELOPMENT_DIRTY' | 'APPLICATION_UPDATE_DEVELOPMENT_REMOTE' | 'APPLICATION_UPDATE_DEVELOPMENT_BRANCH' | 'APPLICATION_UPDATE_DEVELOPMENT_AHEAD' | 'APPLICATION_UPDATE_DEVELOPMENT_DIVERGED';"
          },
          {
            "name": "QuantSkillsInstalledAgentTemplate",
            "declaration": "export interface QuantSkillsInstalledAgentTemplate {\n    readonly version: QuantSkillsInstalledVersion;\n    readonly name: string;\n    readonly description: string;\n    readonly instructions: string;\n    readonly requires: readonly QuantSkillsAssetId[];\n    readonly promptForm?: QuantSkillsPromptFormResult;\n}"
          },
          {
            "name": "QuantSkillsInstalledSnapshot",
            "declaration": "export interface QuantSkillsInstalledSnapshot {\n    readonly versions: readonly QuantSkillsInstalledVersion[];\n}"
          },
          {
            "name": "QuantSkillsInstalledVersion",
            "declaration": "export interface QuantSkillsInstalledVersion {\n    readonly versionId: QuantSkillsInstalledVersionId;\n    readonly assetId: QuantSkillsAssetId;\n    readonly kind: QuantSkillsAssetKind;\n    readonly repository: string;\n    readonly commit: QuantSkillsCommitSha;\n    readonly declaration: QuantSkillsDeclarationFile;\n    readonly treeDigest: QuantSkillsTreeDigest;\n    readonly fileCount: number;\n    readonly totalBytes: number;\n    readonly installedAt: number;\n    readonly exposure: 'skill-registry' | 'agent-template';\n    readonly origin: 'catalog' | 'local-authoring';\n    readonly declarationTitleZh?: string;\n}"
          },
          {
            "name": "QuantSkillsInstalledVersionId",
            "declaration": "export type QuantSkillsInstalledVersionId = Branded<'QuantSkillsInstalledVersionId'>;"
          },
          {
            "name": "QuantSkillsInstallRequest",
            "declaration": "export interface QuantSkillsInstallRequest {\n    readonly assetId: QuantSkillsAssetId;\n    readonly observedSnapshotId: QuantSkillsSnapshotId;\n    readonly observedCommit: QuantSkillsCommitSha;\n}"
          },
          {
            "name": "QuantSkillsManualSkillSaveRequest",
            "declaration": "export interface QuantSkillsManualSkillSaveRequest {\n    readonly markdown: string;\n    readonly mode: 'create' | 'edit' | 'copy';\n    readonly sourceVersionId?: QuantSkillsInstalledVersionId;\n    readonly copyAssetId?: string;\n}"
          },
          {
            "name": "QuantSkillsPromptFormAdaptation",
            "declaration": "export interface QuantSkillsPromptFormAdaptation {\n    readonly code: 'number-default-string';\n    readonly fieldKey: string;\n}"
          },
          {
            "name": "QuantSkillsPromptFormField",
            "declaration": "export interface QuantSkillsPromptFormField {\n    readonly key: string;\n    readonly label: string;\n    readonly type: QuantSkillsPromptFormFieldType;\n    readonly required?: boolean;\n    readonly placeholder?: string;\n    readonly help?: string;\n    readonly default?: string | number;\n    readonly options?: readonly QuantSkillsPromptFormOption[];\n}"
          },
          {
            "name": "QuantSkillsPromptFormFieldType",
            "declaration": "export type QuantSkillsPromptFormFieldType = 'text' | 'textarea' | 'select' | 'date' | 'number';"
          },
          {
            "name": "QuantSkillsPromptFormOption",
            "declaration": "export interface QuantSkillsPromptFormOption {\n    readonly value: string;\n    readonly label: string;\n}"
          },
          {
            "name": "QuantSkillsPromptFormResult",
            "declaration": "export type QuantSkillsPromptFormResult = { readonly status: 'ready'; readonly form: QuantSkillsPromptFormV1; readonly adaptations?: readonly QuantSkillsPromptFormAdaptation[]; } | { readonly status: 'invalid'; readonly reason: string; };"
          },
          {
            "name": "QuantSkillsPromptFormTask",
            "declaration": "export interface QuantSkillsPromptFormTask {\n    readonly placeholder?: string;\n    readonly required?: boolean;\n}"
          },
          {
            "name": "QuantSkillsPromptFormV1",
            "declaration": "export interface QuantSkillsPromptFormV1 {\n    readonly version: 1;\n    readonly task?: QuantSkillsPromptFormTask;\n    readonly fields: readonly QuantSkillsPromptFormField[];\n    readonly promptTemplate: string;\n}"
          },
          {
            "name": "QuantSkillsResolvedInstalledSkill",
            "declaration": "export interface QuantSkillsResolvedInstalledSkill {\n    readonly version: QuantSkillsInstalledVersion;\n    readonly definition: SkillDefinition;\n    readonly promptForm?: import('./types.ts').QuantSkillsPromptFormResult;\n}"
          },
          {
            "name": "QuantSkillsSnapshotId",
            "declaration": "export type QuantSkillsSnapshotId = Branded<'QuantSkillsSnapshotId'>;"
          },
          {
            "name": "QuantSkillsTreeDigest",
            "declaration": "export type QuantSkillsTreeDigest = Branded<'QuantSkillsTreeDigest'>;"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Event-stream connection state changed.",
        "summary": "Event-stream connection state changed.",
        "tags": [
          {
            "name": "param",
            "argument": "status",
            "comment": "- current Host-owned delivery state.",
            "text": "@param status - current Host-owned delivery state.\r\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\r\n * Event-stream connection state changed.\r\n * @param status - current Host-owned delivery state.\r\n * @mode emit\r\n */",
        "name": "quantskills/catalog-sync-status",
        "mode": "emit",
        "signature": "'quantskills/catalog-sync-status'(status: QuantSkillsCatalogSyncStatus): void"
      },
      {
        "description": "A new trusted official catalog snapshot committed after an event-stream hint.",
        "summary": "A new trusted official catalog snapshot committed after an event-stream hint.",
        "tags": [
          {
            "name": "param",
            "argument": "snapshot",
            "comment": "- bounded catalog projection fetched from the configured trusted URL.",
            "text": "@param snapshot - bounded catalog projection fetched from the configured trusted URL.\r\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\r\n * A new trusted official catalog snapshot committed after an event-stream hint.\r\n * @param snapshot - bounded catalog projection fetched from the configured trusted URL.\r\n * @mode emit\r\n */",
        "name": "quantskills/catalog-updated",
        "mode": "emit",
        "signature": "'quantskills/catalog-updated'(snapshot: QuantSkillsCatalogSnapshot): void"
      }
    ],
    "objects": []
  },
}
