/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DataCategory, DataFetch, DataImport, DataQuery, DataResult, DataSummary, PandaMcpStatus } from '@deepseek-ai/dsh-panda-mcp/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$70616e64614d6370 {
    authenticate: (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
    databaseCategorize: (input: { id: string; category: DataCategory; }, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    databaseFetch: (input: DataFetch, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    databaseImport: (input: DataImport, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    databaseList: (signal?: AbortSignal) => Promise<RemoteResult<DataSummary[]>>
    databasePreview: (input: { id: string; }, signal?: AbortSignal) => Promise<RemoteResult<DataResult>>
    databaseQuery: (input: DataQuery, signal?: AbortSignal) => Promise<RemoteResult<DataResult>>
    databaseRefresh: (input: { id: string; }, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    databaseRemove: (input: { id: string; }, signal?: AbortSignal) => Promise<RemoteResult<void>>
    logout: (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
    refresh: (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
    status: (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
  }
  interface TypertRemoteMap {
    'pandaMcp/authenticate': (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
    'pandaMcp/databaseCategorize': (input: { id: string; category: DataCategory; }, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    'pandaMcp/databaseFetch': (input: DataFetch, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    'pandaMcp/databaseImport': (input: DataImport, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    'pandaMcp/databaseList': (signal?: AbortSignal) => Promise<RemoteResult<DataSummary[]>>
    'pandaMcp/databasePreview': (input: { id: string; }, signal?: AbortSignal) => Promise<RemoteResult<DataResult>>
    'pandaMcp/databaseQuery': (input: DataQuery, signal?: AbortSignal) => Promise<RemoteResult<DataResult>>
    'pandaMcp/databaseRefresh': (input: { id: string; }, signal?: AbortSignal) => Promise<RemoteResult<DataSummary>>
    'pandaMcp/databaseRemove': (input: { id: string; }, signal?: AbortSignal) => Promise<RemoteResult<void>>
    'pandaMcp/logout': (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
    'pandaMcp/refresh': (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
    'pandaMcp/status': (signal?: AbortSignal) => Promise<RemoteResult<PandaMcpStatus>>
  }
  interface TypertRemoteNamespaceMap {
    'pandaMcp': TypertRemoteNamespace$70616e64614d6370
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
