/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const JsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema))])
const JsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2))])
const JsonValueRemoteCodec$schema3 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema3))])
const JsonValueRemoteCodec$schema4 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema4))])
const JsonValueRemoteCodec$schema5 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema5)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5))])
const JsonValueRemoteCodec$schema6 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema6))])
const JsonValueRemoteCodec$schema7 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema7)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema7))])
const JsonValueRemoteCodec$schema8 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema8)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema8))])
const _deepseek_ai_dsh_panda_mcp_pandaMcp_authenticate_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'phase': z.union([z.literal("disconnected"), z.literal("authenticating"), z.literal("connected"), z.literal("needs_auth"), z.literal("error")]).readonly(),
  'url': z.string().readonly(),
  'toolCount': z.number().readonly(),
  'toolNames': z.array(z.string()).readonly(),
  'message': z.string().readonly(),
  'authorizationUrl': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseCategorize_parameter_0$schema = z.object({
  'id': z.string(),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseCategorize_result$schema = z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema8)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema8))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseFetch_parameter_0$schema = z.object({
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema3))])).optional(),
  'filename': z.string().optional(),
}),
  'kind': z.union([z.literal("timeseries"), z.literal("table"), z.literal("auto")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]).optional(),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseFetch_result$schema = z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema4))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseImport_parameter_0$schema = z.object({
  'name': z.string(),
  'format': z.union([z.literal("csv"), z.literal("json")]),
  'content': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table"), z.literal("auto")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]).optional(),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseImport_result$schema = z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseList_result$schema = z.array(z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
}))
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databasePreview_parameter_0$schema = z.object({
  'id': z.string(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databasePreview_result$schema = z.object({
  'dataset': z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema6))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
}),
  'status': z.union([z.literal("hit"), z.literal("refreshed"), z.literal("insufficient")]),
  'reasons': z.array(z.string()),
  'rows': z.array(z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema6))]))),
  'total': z.number(),
  'nextOffset': z.number().optional(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseQuery_parameter_0$schema = z.object({
  'id': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'minRows': z.number().optional(),
  'limit': z.number().optional(),
  'offset': z.number().optional(),
  'refresh': z.boolean().optional(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseQuery_result$schema = z.object({
  'dataset': z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema5)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
}),
  'status': z.union([z.literal("hit"), z.literal("refreshed"), z.literal("insufficient")]),
  'reasons': z.array(z.string()),
  'rows': z.array(z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema5)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5))]))),
  'total': z.number(),
  'nextOffset': z.number().optional(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRefresh_parameter_0$schema = z.object({
  'id': z.string(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRefresh_result$schema = z.object({
  'id': z.string(),
  'kind': z.union([z.literal("timeseries"), z.literal("table")]),
  'category': z.union([z.literal("market"), z.literal("news"), z.literal("fundamental"), z.literal("other")]),
  'columns': z.array(z.string()),
  'rowCount': z.number(),
  'fetchedAt': z.string(),
  'expiresAt': z.string(),
  'from': z.string().optional(),
  'to': z.string().optional(),
  'bytes': z.number(),
  'name': z.string(),
  'source': z.object({
  'kind': z.union([z.literal("file"), z.literal("http"), z.literal("pandadata")]),
  'url': z.string().optional(),
  'method': z.string().optional(),
  'params': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema7)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema7))])).optional(),
  'filename': z.string().optional(),
}),
  'dateColumn': z.string().optional(),
  'ttlSeconds': z.number(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRemove_parameter_0$schema = z.object({
  'id': z.string(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRemove_result$schema = z.void()
const _deepseek_ai_dsh_panda_mcp_pandaMcp_logout_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'phase': z.union([z.literal("disconnected"), z.literal("authenticating"), z.literal("connected"), z.literal("needs_auth"), z.literal("error")]).readonly(),
  'url': z.string().readonly(),
  'toolCount': z.number().readonly(),
  'toolNames': z.array(z.string()).readonly(),
  'message': z.string().readonly(),
  'authorizationUrl': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_refresh_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'phase': z.union([z.literal("disconnected"), z.literal("authenticating"), z.literal("connected"), z.literal("needs_auth"), z.literal("error")]).readonly(),
  'url': z.string().readonly(),
  'toolCount': z.number().readonly(),
  'toolNames': z.array(z.string()).readonly(),
  'message': z.string().readonly(),
  'authorizationUrl': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_panda_mcp_pandaMcp_status_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'phase': z.union([z.literal("disconnected"), z.literal("authenticating"), z.literal("connected"), z.literal("needs_auth"), z.literal("error")]).readonly(),
  'url': z.string().readonly(),
  'toolCount': z.number().readonly(),
  'toolNames': z.array(z.string()).readonly(),
  'message': z.string().readonly(),
  'authorizationUrl': z.string().readonly().optional(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-panda-mcp',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/authenticate',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'authenticate',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#PandaMcpStatus',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_authenticate_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":275,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseCategorize',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseCategorize',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseCategorize:input',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseCategorize_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataSummary',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseCategorize_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":248,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseFetch',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseFetch',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataFetch',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseFetch_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataSummary',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseFetch_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":238,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseImport',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseImport',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataImport',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseImport_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataSummary',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseImport_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":236,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseList',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseList',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseList:result',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseList_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":234,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databasePreview',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databasePreview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databasePreview:input',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databasePreview_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataResult',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databasePreview_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":242,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseQuery',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseQuery',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataQuery',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseQuery_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataResult',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseQuery_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":240,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseRefresh',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseRefresh',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseRefresh:input',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRefresh_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#DataSummary',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRefresh_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":244,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseRemove',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'databaseRemove',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseRemove:input',
            schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRemove_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp#pandaMcp/databaseRemove:result',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_databaseRemove_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":246,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/logout',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'logout',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#PandaMcpStatus',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_logout_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":302,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/refresh',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'refresh',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#PandaMcpStatus',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_refresh_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":284,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-panda-mcp#pandaMcp/status',
      service: 'pandaMcp',
      namespace: 'pandaMcp',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-panda-mcp/types#PandaMcpStatus',
        schema: _deepseek_ai_dsh_panda_mcp_pandaMcp_status_result$schema,
      },
      sourceLocation: {"file":"packages/panda-mcp/src/index.ts","line":269,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "公网 PandaData MCP 网关。",
        "summary": "公网 PandaData MCP 网关。",
        "tags": [],
        "jsDoc": "/** 公网 PandaData MCP 网关。 */",
        "key": "pandaMcp",
        "exportName": "PandaMcpGateway",
        "members": [
          {
            "kind": "method",
            "name": "databaseList",
            "signature": "@Remote databaseList(signal?: AbortSignal): Promise<DataSummary[]>"
          },
          {
            "kind": "method",
            "name": "databaseImport",
            "signature": "@Remote databaseImport(input: DataImport, signal?: AbortSignal): Promise<DataSummary>"
          },
          {
            "kind": "method",
            "name": "databaseFetch",
            "signature": "@Remote databaseFetch(input: DataFetch, signal?: AbortSignal): Promise<DataSummary>"
          },
          {
            "kind": "method",
            "name": "databaseQuery",
            "signature": "@Remote databaseQuery(input: DataQuery, signal?: AbortSignal): Promise<DataResult>"
          },
          {
            "kind": "method",
            "name": "databasePreview",
            "signature": "@Remote databasePreview(input: { id: string }, signal?: AbortSignal): Promise<DataResult>"
          },
          {
            "kind": "method",
            "name": "databaseRefresh",
            "signature": "@Remote databaseRefresh(input: { id: string }, signal?: AbortSignal): Promise<DataSummary>"
          },
          {
            "kind": "method",
            "name": "databaseRemove",
            "signature": "@Remote databaseRemove(input: { id: string }, signal?: AbortSignal): Promise<void>"
          },
          {
            "kind": "method",
            "name": "databaseCategorize",
            "signature": "@Remote databaseCategorize(input: { id: string; category: DataCategory }, signal?: AbortSignal): Promise<DataSummary>"
          },
          {
            "kind": "method",
            "name": "useConnector",
            "signature": "useConnector(connector: PandaMcpSessionConnector): void",
            "summary": "测试替换会话工厂。",
            "jsDoc": "/** 测试替换会话工厂。 */"
          },
          {
            "kind": "method",
            "name": "useOpenAuthorization",
            "signature": "useOpenAuthorization(openAuthorization: (url: URL) => void | Promise<void>): void",
            "summary": "测试替换打开浏览器。",
            "jsDoc": "/** 测试替换打开浏览器。 */"
          },
          {
            "kind": "method",
            "name": "status",
            "signature": "@Remote status(signal?: AbortSignal): Promise<PandaMcpStatus>"
          },
          {
            "kind": "method",
            "name": "authenticate",
            "signature": "@Remote authenticate(signal?: AbortSignal): Promise<PandaMcpStatus>"
          },
          {
            "kind": "method",
            "name": "refresh",
            "signature": "@Remote async refresh(signal?: AbortSignal): Promise<PandaMcpStatus>",
            "summary": "用已保存 token 静默重连；没有 token 时只返回当前状态，不打开浏览器。",
            "jsDoc": "/** 用已保存 token 静默重连；没有 token 时只返回当前状态，不打开浏览器。 */"
          },
          {
            "kind": "method",
            "name": "logout",
            "signature": "@Remote async logout(signal?: AbortSignal): Promise<PandaMcpStatus>"
          },
          {
            "kind": "method",
            "name": "ensureAuthenticated",
            "signature": "async ensureAuthenticated(signal?: AbortSignal): Promise<PandaMcpStatus>"
          }
        ],
        "types": [
          {
            "name": "DataCategory",
            "declaration": "export type DataCategory = 'market' | 'news' | 'fundamental' | 'other';"
          },
          {
            "name": "DataFetch",
            "declaration": "export interface DataFetch {\n    name: string;\n    source: DataSource;\n    kind: 'timeseries' | 'table' | 'auto';\n    category?: DataCategory;\n    dateColumn?: string;\n    ttlSeconds: number;\n}"
          },
          {
            "name": "DataImport",
            "declaration": "export interface DataImport {\n    name: string;\n    format: 'csv' | 'json';\n    content: string;\n    kind: 'timeseries' | 'table' | 'auto';\n    category?: DataCategory;\n    dateColumn?: string;\n    ttlSeconds: number;\n}"
          },
          {
            "name": "DataQuery",
            "declaration": "export interface DataQuery {\n    id: string;\n    from?: string;\n    to?: string;\n    minRows?: number;\n    limit?: number;\n    offset?: number;\n    refresh?: boolean;\n}"
          },
          {
            "name": "DataResult",
            "declaration": "export interface DataResult {\n    dataset: DataSummary;\n    status: 'hit' | 'refreshed' | 'insufficient';\n    reasons: string[];\n    rows: Record<string, JsonValue>[];\n    total: number;\n    nextOffset?: number;\n}"
          },
          {
            "name": "DataSource",
            "declaration": "export interface DataSource {\n    kind: 'file' | 'http' | 'pandadata';\n    url?: string;\n    method?: string;\n    params?: Record<string, JsonValue>;\n    filename?: string;\n}"
          },
          {
            "name": "DataSummary",
            "declaration": "export interface DataSummary extends DataFetch {\n    id: string;\n    kind: 'timeseries' | 'table';\n    category: DataCategory;\n    columns: string[];\n    rowCount: number;\n    fetchedAt: string;\n    expiresAt: string;\n    from?: string;\n    to?: string;\n    bytes: number;\n}"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue; };"
          },
          {
            "name": "PandaMcpOAuthSnapshot",
            "declaration": "export interface PandaMcpOAuthSnapshot {\n    readonly client?: OAuthClientInformationMixed;\n    readonly tokens?: OAuthTokens;\n    readonly codeVerifier?: string;\n}"
          },
          {
            "name": "PandaMcpOAuthStore",
            "declaration": "export class PandaMcpOAuthStore {\n    load(): Promise<PandaMcpOAuthSnapshot>;\n    current(): PandaMcpOAuthSnapshot;\n    hasAccessToken(): boolean;\n    saveClient(client: OAuthClientInformationMixed): Promise<void>;\n    saveTokens(tokens: OAuthTokens): Promise<void>;\n    saveCodeVerifier(codeVerifier: string): Promise<void>;\n    clear(scope: 'all' | 'client' | 'tokens' | 'verifier' = 'all'): Promise<void>;\n}"
          },
          {
            "name": "PandaMcpPhase",
            "declaration": "export type PandaMcpPhase = 'disconnected' | 'authenticating' | 'connected' | 'needs_auth' | 'error';"
          },
          {
            "name": "PandaMcpSessionConnector",
            "declaration": "export interface PandaMcpSessionConnector {\n    connect(args: { url: string; store: PandaMcpOAuthStore; redirectUrl: string; openAuthorization: (url: URL) => void | Promise<void>; signal?: AbortSignal; }): Promise<{ client: Client; close: () => Promise<void>; }>;\n}"
          },
          {
            "name": "PandaMcpStatus",
            "declaration": "export interface PandaMcpStatus {\n    readonly ok: true;\n    readonly phase: PandaMcpPhase;\n    readonly url: string;\n    readonly toolCount: number;\n    readonly toolNames: readonly string[];\n    readonly message: string;\n    readonly authorizationUrl?: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
